/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.obzen.spark.batch.inykang.model;

import java.io.Serializable;

/**
 * VST_ORG_LOG definition.
 * <pvCnt>
 * Code generated by Apache Ignite Schema Import utility: 01/26/2017.
 */
public class LogBaseDetail implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    private String eventTimestamp;
    private String sessionId;
    private String uuid;
    private String custId;
    private String cookieId;
    private String sex;
    private String age;
    private String place;
    private String custGrade;
    private String eventTypeCd;
    private String clickCd;
    private String deviceType;
    private String appWebType;
    private String browserNm;
    private String ipAddr;
    private String inboundChnlSrc;
    private String inboundChnlMedium;
    private String inboundChnlCampaign;
    private String inboundChnlKeyword;
    private String refererUri;
    private String currPageUri;
    private String pvType;
    private String searchWord;
    private String searchResultType;
    private String productCd;
    private String productCatgL;
    private String productCatgM;
    private String productCatgS;
    private String productBrandCd;
    private String basketId;
    private String orderId;

    /**
     * Extension
     **/
    private int pageSeq = 0;
    private long stayTime = 0L;
    private long amount = 0L;
    /** Extension **/

    /**
     * Empty constructor.
     */
    public LogBaseDetail() {
        // No-op.
    }

    /**
     * Org log constructor.
     */
    public LogBaseDetail(
            String eventTimestamp,
            String sessionId,
            String uuid,
            String custId,
            String cookieId,
            String sex,
            String age,
            String place,
            String custGrade,
            String eventTypeCd,
            String clickCd,
            String deviceType,
            String appWebType,
            String browserNm,
            String ipAddr,
            String inboundChnlSrc,
            String inboundChnlMedium,
            String inboundChnlCampaign,
            String inboundChnlKeyword,
            String refererUri,
            String currPageUri,
            String pvType,
            String searchWord,
            String searchResultType,
            String productCd,
            String productCatgL,
            String productCatgM,
            String productCatgS,
            String productBrandCd,
            String basketId,
            String orderId
    ) {
        this.eventTimestamp = eventTimestamp;
        this.sessionId = sessionId;
        this.uuid = uuid;
        this.custId = custId;
        this.cookieId = cookieId;
        this.sex = sex;
        this.age = age;
        this.place = place;
        this.custGrade = custGrade;
        this.eventTypeCd = eventTypeCd;
        this.clickCd = clickCd;
        this.deviceType = deviceType;
        this.appWebType = appWebType;
        this.browserNm = browserNm;
        this.ipAddr = ipAddr;
        this.inboundChnlSrc = inboundChnlSrc;
        this.inboundChnlMedium = inboundChnlMedium;
        this.inboundChnlCampaign = inboundChnlCampaign;
        this.inboundChnlKeyword = inboundChnlKeyword;
        this.refererUri = refererUri;
        this.currPageUri = currPageUri;
        this.pvType = pvType;
        this.searchWord = searchWord;
        this.searchResultType = searchResultType;
        this.productCd = productCd;
        this.productCatgL = productCatgL;
        this.productCatgM = productCatgM;
        this.productCatgS = productCatgS;
        this.productBrandCd = productBrandCd;
        this.basketId = basketId;
        this.orderId = orderId;
    }

    /**
     * Full constructor.
     */
    public LogBaseDetail(
            String eventTimestamp,
            String sessionId,
            String uuid,
            String custId,
            String cookieId,
            String sex,
            String age,
            String place,
            String custGrade,
            String eventTypeCd,
            String clickCd,
            String deviceType,
            String appWebType,
            String browserNm,
            String ipAddr,
            String inboundChnlSrc,
            String inboundChnlMedium,
            String inboundChnlCampaign,
            String inboundChnlKeyword,
            String refererUri,
            String currPageUri,
            int pageSeq,
            String pvType,
            int stayTime,
            String searchWord,
            String searchResultType,
            String productCd,
            String productCatgL,
            String productCatgM,
            String productCatgS,
            String productBrandCd,
            String basketId,
            String orderId,
            long amount
    ) {
        this.eventTimestamp = eventTimestamp;
        this.sessionId = sessionId;
        this.uuid = uuid;
        this.custId = custId;
        this.cookieId = cookieId;
        this.sex = sex;
        this.age = age;
        this.place = place;
        this.custGrade = custGrade;
        this.eventTypeCd = eventTypeCd;
        this.clickCd = clickCd;
        this.deviceType = deviceType;
        this.appWebType = appWebType;
        this.browserNm = browserNm;
        this.ipAddr = ipAddr;
        this.inboundChnlSrc = inboundChnlSrc;
        this.inboundChnlMedium = inboundChnlMedium;
        this.inboundChnlCampaign = inboundChnlCampaign;
        this.inboundChnlKeyword = inboundChnlKeyword;
        this.refererUri = refererUri;
        this.currPageUri = currPageUri;
        this.pageSeq = pageSeq;
        this.pvType = pvType;
        this.stayTime = stayTime;
        this.searchWord = searchWord;
        this.searchResultType = searchResultType;
        this.productCd = productCd;
        this.productCatgL = productCatgL;
        this.productCatgM = productCatgM;
        this.productCatgS = productCatgS;
        this.productBrandCd = productBrandCd;
        this.basketId = basketId;
        this.orderId = orderId;
        this.amount = amount;
    }

    /**
     * Gets eventTimestamp.
     *
     * @return Value for eventTimestamp.
     */
    public String getEventTimestamp() {
        return eventTimestamp;
    }

    /**
     * Sets eventTimestamp.
     *
     * @param eventTimestamp New value for eventTimestamp.
     */
    public void setEventTimestamp(String eventTimestamp) {
        this.eventTimestamp = eventTimestamp;
    }

    /**
     * Gets sessionId.
     *
     * @return Value for sessionId.
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets sessionId.
     *
     * @param sessionId New value for sessionId.
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * Gets uuid.
     *
     * @return Value for uuid.
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets uuid.
     *
     * @param uuid New value for uuid.
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Gets custId.
     *
     * @return Value for custId.
     */
    public String getCustId() {
        return custId;
    }

    /**
     * Sets custId.
     *
     * @param custId New value for custId.
     */
    public void setCustId(String custId) {
        this.custId = custId;
    }

    /**
     * Gets cookieId.
     *
     * @return Value for cookieId.
     */
    public String getCookieId() {
        return cookieId;
    }

    /**
     * Sets cookieId.
     *
     * @param cookieId New value for cookieId.
     */
    public void setCookieId(String cookieId) {
        this.cookieId = cookieId;
    }

    /**
     * Gets sex.
     *
     * @return Value for sex.
     */
    public String getSex() {
        return sex;
    }

    /**
     * Sets sex.
     *
     * @param sex New value for sex.
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * Gets age.
     *
     * @return Value for age.
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets age.
     *
     * @param age New value for age.
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * Gets place.
     *
     * @return Value for place.
     */
    public String getPlace() {
        return place;
    }

    /**
     * Sets place.
     *
     * @param place New value for place.
     */
    public void setPlace(String place) {
        this.place = place;
    }

    /**
     * Gets custGrade.
     *
     * @return Value for custGrade.
     */
    public String getCustGrade() {
        return custGrade;
    }

    /**
     * Sets custGrade.
     *
     * @param custGrade New value for custGrade.
     */
    public void setCustGrade(String custGrade) {
        this.custGrade = custGrade;
    }

    /**
     * Gets eventTypeCd.
     *
     * @return Value for eventTypeCd.
     */
    public String getEventTypeCd() {
        return eventTypeCd;
    }

    /**
     * Sets eventTypeCd.
     *
     * @param eventTypeCd New value for eventTypeCd.
     */
    public void setEventTypeCd(String eventTypeCd) {
        this.eventTypeCd = eventTypeCd;
    }

    /**
     * Gets clickCd.
     *
     * @return Value for clickCd.
     */
    public String getClickCd() {
        return clickCd;
    }

    /**
     * Sets clickCd.
     *
     * @param clickCd New value for clickCd.
     */
    public void setClickCd(String clickCd) {
        this.clickCd = clickCd;
    }

    /**
     * Gets deviceType.
     *
     * @return Value for deviceType.
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets deviceType.
     *
     * @param deviceType New value for deviceType.
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * Gets appWebType.
     *
     * @return Value for appWebType.
     */
    public String getAppWebType() {
        return appWebType;
    }

    /**
     * Sets appWebType.
     *
     * @param appWebType New value for appWebType.
     */
    public void setAppWebType(String appWebType) {
        this.appWebType = appWebType;
    }

    /**
     * Gets browserNm.
     *
     * @return Value for browserNm.
     */
    public String getBrowserNm() {
        return browserNm;
    }

    /**
     * Sets browserNm.
     *
     * @param browserNm New value for browserNm.
     */
    public void setBrowserNm(String browserNm) {
        this.browserNm = browserNm;
    }

    /**
     * Gets ipAddr.
     *
     * @return Value for ipAddr.
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * Sets ipAddr.
     *
     * @param ipAddr New value for ipAddr.
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    /**
     * Gets inboundChnlSrc.
     *
     * @return Value for inboundChnlSrc.
     */
    public String getInboundChnlSrc() {
        return inboundChnlSrc;
    }

    /**
     * Sets inboundChnlSrc.
     *
     * @param inboundChnlSrc New value for inboundChnlSrc.
     */
    public void setInboundChnlSrc(String inboundChnlSrc) {
        this.inboundChnlSrc = inboundChnlSrc;
    }

    /**
     * Gets inboundChnlMedium.
     *
     * @return Value for inboundChnlMedium.
     */
    public String getInboundChnlMedium() {
        return inboundChnlMedium;
    }

    /**
     * Sets inboundChnlMedium.
     *
     * @param inboundChnlMedium New value for inboundChnlMedium.
     */
    public void setInboundChnlMedium(String inboundChnlMedium) {
        this.inboundChnlMedium = inboundChnlMedium;
    }

    /**
     * Gets inboundChnlCampaign.
     *
     * @return Value for inboundChnlCampaign.
     */
    public String getInboundChnlCampaign() {
        return inboundChnlCampaign;
    }

    /**
     * Sets inboundChnlCampaign.
     *
     * @param inboundChnlCampaign New value for inboundChnlCampaign.
     */
    public void setInboundChnlCampaign(String inboundChnlCampaign) {
        this.inboundChnlCampaign = inboundChnlCampaign;
    }

    /**
     * Gets inboundChnlKeyword.
     *
     * @return Value for inboundChnlKeyword.
     */
    public String getInboundChnlKeyword() {
        return inboundChnlKeyword;
    }

    /**
     * Sets inboundChnlKeyword.
     *
     * @param inboundChnlKeyword New value for inboundChnlKeyword.
     */
    public void setInboundChnlKeyword(String inboundChnlKeyword) {
        this.inboundChnlKeyword = inboundChnlKeyword;
    }

    /**
     * Gets refererUri.
     *
     * @return Value for refererUri.
     */
    public String getRefererUri() {
        return refererUri;
    }

    /**
     * Sets refererUri.
     *
     * @param refererUri New value for refererUri.
     */
    public void setRefererUri(String refererUri) {
        this.refererUri = refererUri;
    }

    /**
     * Gets currPageUri.
     *
     * @return Value for currPageUri.
     */
    public String getCurrPageUri() {
        return currPageUri;
    }

    /**
     * Sets currPageUri.
     *
     * @param currPageUri New value for currPageUri.
     */
    public void setCurrPageUri(String currPageUri) {
        this.currPageUri = currPageUri;
    }

    /**
     * Gets pvType.
     *
     * @return Value for pvType.
     */
    public String getPvType() {
        return pvType;
    }

    /**
     * Sets pvType.
     *
     * @param pvType New value for pvType.
     */
    public void setPvType(String pvType) {
        this.pvType = pvType;
    }

    /**
     * Gets searchWord.
     *
     * @return Value for searchWord.
     */
    public String getSearchWord() {
        return searchWord;
    }

    /**
     * Sets searchWord.
     *
     * @param searchWord New value for searchWord.
     */
    public void setSearchWord(String searchWord) {
        this.searchWord = searchWord;
    }

    /**
     * Gets searchResultType.
     *
     * @return Value for searchResultType.
     */
    public String getSearchResultType() {
        return searchResultType;
    }

    /**
     * Sets searchResultType.
     *
     * @param searchResultType New value for searchResultType.
     */
    public void setSearchResultType(String searchResultType) {
        this.searchResultType = searchResultType;
    }

    /**
     * Gets productCd.
     *
     * @return Value for productCd.
     */
    public String getProductCd() {
        return productCd;
    }

    /**
     * Sets productCd.
     *
     * @param productCd New value for productCd.
     */
    public void setProductCd(String productCd) {
        this.productCd = productCd;
    }

    /**
     * Gets productCatgL.
     *
     * @return Value for productCatgL.
     */
    public String getProductCatgL() {
        return productCatgL;
    }

    /**
     * Sets productCatgL.
     *
     * @param productCatgL New value for productCatgL.
     */
    public void setProductCatgL(String productCatgL) {
        this.productCatgL = productCatgL;
    }

    /**
     * Gets productCatgM.
     *
     * @return Value for productCatgM.
     */
    public String getProductCatgM() {
        return productCatgM;
    }

    /**
     * Sets productCatgM.
     *
     * @param productCatgM New value for productCatgM.
     */
    public void setProductCatgM(String productCatgM) {
        this.productCatgM = productCatgM;
    }

    /**
     * Gets productCatgS.
     *
     * @return Value for productCatgS.
     */
    public String getProductCatgS() {
        return productCatgS;
    }

    /**
     * Sets productCatgS.
     *
     * @param productCatgS New value for productCatgS.
     */
    public void setProductCatgS(String productCatgS) {
        this.productCatgS = productCatgS;
    }

    /**
     * Gets productBrandCd.
     *
     * @return Value for productBrandCd.
     */
    public String getProductBrandCd() {
        return productBrandCd;
    }

    /**
     * Sets productBrandCd.
     *
     * @param productBrandCd New value for productBrandCd.
     */
    public void setProductBrandCd(String productBrandCd) {
        this.productBrandCd = productBrandCd;
    }

    public String getBasketId() {
        return basketId;
    }

    public void setBasketId(String basketId) {
        this.basketId = basketId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * Extension
     **/
    /**
     * Gets pageSeq.
     *
     * @return Value for pageSeq.
     */
    public int getPageSeq() {
        return pageSeq;
    }

    /**
     * Sets pageSeq.
     *
     * @param pageSeq New value for pageSeq.
     */
    public void setPageSeq(int pageSeq) {
        this.pageSeq = pageSeq;
    }


    /**
     * Gets stayTime.
     *
     * @return Value for stayTime.
     */
    public long getStayTime() {
        return stayTime;
    }

    /**
     * Sets stayTime.
     *
     * @param stayTime New value for stayTime.
     */
    public void setStayTime(long stayTime) {
        this.stayTime = stayTime;
    }

    public long getAmount() { return amount; }

    public void setAmount(long amount) { this.amount = amount; }
    /** Extension **/

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("LogBaseDetail [eventTimestamp=" + eventTimestamp);
        sb.append(", sessionId=" + sessionId);
        sb.append(", uuid=" + uuid);
        sb.append(", custId=" + custId);
        sb.append(", cookieId=" + cookieId);
        sb.append(", sex=" + sex);
        sb.append(", age=" + age);
        sb.append(", place=" + place);
        sb.append(", custGrade=" + custGrade);
        sb.append(", eventTypeCd=" + eventTypeCd);
        sb.append(", clickCd=" + clickCd);
        sb.append(", deviceType=" + deviceType);
        sb.append(", appWebType=" + appWebType);
        sb.append(", browserNm=" + browserNm);
        sb.append(", ipAddr=" + ipAddr);
        sb.append(", inboundChnlSrc=" + inboundChnlSrc);
        sb.append(", inboundChnlMedium=" + inboundChnlMedium);
        sb.append(", inboundChnlCampaign=" + inboundChnlCampaign);
        sb.append(", inboundChnlKeyword=" + inboundChnlKeyword);
        sb.append(", refererUri=" + refererUri);
        sb.append(", currPageUri=" + currPageUri);
        sb.append(", pageSeq=" + pageSeq);
        sb.append(", pvType=" + pvType);
        sb.append(", stayTime=" + stayTime);
        sb.append(", searchWord=" + searchWord);
        sb.append(", searchResultType=" + searchResultType);
        sb.append(", productCd=" + productCd);
        sb.append(", productCatgL=" + productCatgL);
        sb.append(", productCatgM=" + productCatgM);
        sb.append(", productCatgS=" + productCatgS);
        sb.append(", productBrandCd=" + productBrandCd);
        sb.append(", basketId=" + basketId);
        sb.append(", orderId=" + orderId);
        sb.append(", amount=" + amount);
        sb.append("]");
        return sb.toString();
    }
}