/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.obzen.spark.batch.inykang.model;

import java.io.Serializable;

/**
 * VST_ORG_LOG definition.
 * <p>
 * Code generated by Apache Ignite Schema Import utility: 05/31/2017.
 */
public class OrgBaseLog implements Serializable {
    /** */
    private static final long serialVersionUID = 0L;

    /**
     * Value for eventTimestamp.
     */

    private String eventTimestamp;

    /**
     * Value for sessionId.
     */

    private String sessionId;

    /**
     * Value for uuid.
     */

    private String uuid;

    /**
     * Value for custId.
     */

    private String custId;

    /**
     * Value for cookieId.
     */

    private String cookieId;

    /**
     * Value for gender.
     */

    private String gender;

    /**
     * Value for age.
     */

    private String age;

    /**
     * Value for areaa.
     */

    private String areaa;

    /**
     * Value for grade.
     */

    private String grade;

    /**
     * Value for eventTypeCd.
     */

    private String eventTypeCd;

    /**
     * Value for clickCd.
     */

    private String clickCd;

    /**
     * Value for deviceType.
     */

    private String deviceType;

    /**
     * Value for appWebType.
     */

    private String appWebType;

    /**
     * Value for browserType.
     */

    private String browserType;

    /**
     * Value for ipAddr.
     */

    private String ipAddr;

    /**
     * Value for inboundChnlSrc.
     */

    private String inboundChnlSrc;

    /**
     * Value for inboundChnlMedium.
     */

    private String inboundChnlMedium;

    /**
     * Value for inboundChnlCampaign.
     */

    private String inboundChnlCampaign;

    /**
     * Value for inboundChnlKeyword.
     */

    private String inboundChnlKeyword;

    /**
     * Value for refererUril.
     */

    private String refererUril;

    /**
     * Value for currPageUri.
     */

    private String currPageUri;

    /**
     * Value for pvType.
     */

    private String pvType;

    /**
     * Value for searchWord.
     */

    private String searchWord;

    /**
     * Value for searchResultNum.
     */

    private String searchResultNum;

    /**
     * Value for productCd.
     */

    private String productCd;

    /**
     * Value for productCatgL.
     */

    private String productCatgL;

    /**
     * Value for productCatgM.
     */

    private String productCatgM;

    /**
     * Value for productCatgS.
     */

    private String productCatgS;

    /**
     * Value for productBrandCd.
     */

    private String productBrandCd;

    /**
     * Value for basketId.
     */

    private String basketId;

    /**
     * Value for orderId.
     */

    private String orderId;

    /**
     * Empty constructor.
     */
    public OrgBaseLog() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public OrgBaseLog(
            String eventTimestamp,
            String sessionId,
            String uuid,
            String custId,
            String cookieId,
            String gender,
            String age,
            String areaa,
            String grade,
            String eventTypeCd,
            String clickCd,
            String deviceType,
            String appWebType,
            String browserType,
            String ipAddr,
            String inboundChnlSrc,
            String inboundChnlMedium,
            String inboundChnlCampaign,
            String inboundChnlKeyword,
            String refererUril,
            String currPageUri,
            String pvType,
            String searchWord,
            String searchResultNum,
            String productCd,
            String productCatgL,
            String productCatgM,
            String productCatgS,
            String productBrandCd,
            String basketId,
            String orderId
    ) {
        this.eventTimestamp = eventTimestamp;
        this.sessionId = sessionId;
        this.uuid = uuid;
        this.custId = custId;
        this.cookieId = cookieId;
        this.gender = gender;
        this.age = age;
        this.areaa = areaa;
        this.grade = grade;
        this.eventTypeCd = eventTypeCd;
        this.clickCd = clickCd;
        this.deviceType = deviceType;
        this.appWebType = appWebType;
        this.browserType = browserType;
        this.ipAddr = ipAddr;
        this.inboundChnlSrc = inboundChnlSrc;
        this.inboundChnlMedium = inboundChnlMedium;
        this.inboundChnlCampaign = inboundChnlCampaign;
        this.inboundChnlKeyword = inboundChnlKeyword;
        this.refererUril = refererUril;
        this.currPageUri = currPageUri;
        this.pvType = pvType;
        this.searchWord = searchWord;
        this.searchResultNum = searchResultNum;
        this.productCd = productCd;
        this.productCatgL = productCatgL;
        this.productCatgM = productCatgM;
        this.productCatgS = productCatgS;
        this.productBrandCd = productBrandCd;
        this.basketId = basketId;
        this.orderId = orderId;
    }

    /**
     * Gets eventTimestamp.
     *
     * @return Value for eventTimestamp.
     */
    public String getEventTimestamp() {
        return eventTimestamp;
    }

    /**
     * Sets eventTimestamp.
     *
     * @param eventTimestamp New value for eventTimestamp.
     */
    public void setEventTimestamp(String eventTimestamp) {
        this.eventTimestamp = eventTimestamp;
    }

    /**
     * Gets sessionId.
     *
     * @return Value for sessionId.
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets sessionId.
     *
     * @param sessionId New value for sessionId.
     */
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    /**
     * Gets uuid.
     *
     * @return Value for uuid.
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * Sets uuid.
     *
     * @param uuid New value for uuid.
     */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    /**
     * Gets custId.
     *
     * @return Value for custId.
     */
    public String getCustId() {
        return custId;
    }

    /**
     * Sets custId.
     *
     * @param custId New value for custId.
     */
    public void setCustId(String custId) {
        this.custId = custId;
    }

    /**
     * Gets cookieId.
     *
     * @return Value for cookieId.
     */
    public String getCookieId() {
        return cookieId;
    }

    /**
     * Sets cookieId.
     *
     * @param cookieId New value for cookieId.
     */
    public void setCookieId(String cookieId) {
        this.cookieId = cookieId;
    }

    /**
     * Gets gender.
     *
     * @return Value for gender.
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets gender.
     *
     * @param gender New value for gender.
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * Gets age.
     *
     * @return Value for age.
     */
    public String getAge() {
        return age;
    }

    /**
     * Sets age.
     *
     * @param age New value for age.
     */
    public void setAge(String age) {
        this.age = age;
    }

    /**
     * Gets areaa.
     *
     * @return Value for areaa.
     */
    public String getAreaa() {
        return areaa;
    }

    /**
     * Sets areaa.
     *
     * @param areaa New value for areaa.
     */
    public void setAreaa(String areaa) {
        this.areaa = areaa;
    }

    /**
     * Gets grade.
     *
     * @return Value for grade.
     */
    public String getGrade() {
        return grade;
    }

    /**
     * Sets grade.
     *
     * @param grade New value for grade.
     */
    public void setGrade(String grade) {
        this.grade = grade;
    }

    /**
     * Gets eventTypeCd.
     *
     * @return Value for eventTypeCd.
     */
    public String getEventTypeCd() {
        return eventTypeCd;
    }

    /**
     * Sets eventTypeCd.
     *
     * @param eventTypeCd New value for eventTypeCd.
     */
    public void setEventTypeCd(String eventTypeCd) {
        this.eventTypeCd = eventTypeCd;
    }

    /**
     * Gets clickCd.
     *
     * @return Value for clickCd.
     */
    public String getClickCd() {
        return clickCd;
    }

    /**
     * Sets clickCd.
     *
     * @param clickCd New value for clickCd.
     */
    public void setClickCd(String clickCd) {
        this.clickCd = clickCd;
    }

    /**
     * Gets deviceType.
     *
     * @return Value for deviceType.
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets deviceType.
     *
     * @param deviceType New value for deviceType.
     */
    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    /**
     * Gets appWebType.
     *
     * @return Value for appWebType.
     */
    public String getAppWebType() {
        return appWebType;
    }

    /**
     * Sets appWebType.
     *
     * @param appWebType New value for appWebType.
     */
    public void setAppWebType(String appWebType) {
        this.appWebType = appWebType;
    }

    /**
     * Gets browserType.
     *
     * @return Value for browserType.
     */
    public String getBrowserType() {
        return browserType;
    }

    /**
     * Sets browserType.
     *
     * @param browserType New value for browserType.
     */
    public void setBrowserType(String browserType) {
        this.browserType = browserType;
    }

    /**
     * Gets ipAddr.
     *
     * @return Value for ipAddr.
     */
    public String getIpAddr() {
        return ipAddr;
    }

    /**
     * Sets ipAddr.
     *
     * @param ipAddr New value for ipAddr.
     */
    public void setIpAddr(String ipAddr) {
        this.ipAddr = ipAddr;
    }

    /**
     * Gets inboundChnlSrc.
     *
     * @return Value for inboundChnlSrc.
     */
    public String getInboundChnlSrc() {
        return inboundChnlSrc;
    }

    /**
     * Sets inboundChnlSrc.
     *
     * @param inboundChnlSrc New value for inboundChnlSrc.
     */
    public void setInboundChnlSrc(String inboundChnlSrc) {
        this.inboundChnlSrc = inboundChnlSrc;
    }

    /**
     * Gets inboundChnlMedium.
     *
     * @return Value for inboundChnlMedium.
     */
    public String getInboundChnlMedium() {
        return inboundChnlMedium;
    }

    /**
     * Sets inboundChnlMedium.
     *
     * @param inboundChnlMedium New value for inboundChnlMedium.
     */
    public void setInboundChnlMedium(String inboundChnlMedium) {
        this.inboundChnlMedium = inboundChnlMedium;
    }

    /**
     * Gets inboundChnlCampaign.
     *
     * @return Value for inboundChnlCampaign.
     */
    public String getInboundChnlCampaign() {
        return inboundChnlCampaign;
    }

    /**
     * Sets inboundChnlCampaign.
     *
     * @param inboundChnlCampaign New value for inboundChnlCampaign.
     */
    public void setInboundChnlCampaign(String inboundChnlCampaign) {
        this.inboundChnlCampaign = inboundChnlCampaign;
    }

    /**
     * Gets inboundChnlKeyword.
     *
     * @return Value for inboundChnlKeyword.
     */
    public String getInboundChnlKeyword() {
        return inboundChnlKeyword;
    }

    /**
     * Sets inboundChnlKeyword.
     *
     * @param inboundChnlKeyword New value for inboundChnlKeyword.
     */
    public void setInboundChnlKeyword(String inboundChnlKeyword) {
        this.inboundChnlKeyword = inboundChnlKeyword;
    }

    /**
     * Gets refererUril.
     *
     * @return Value for refererUril.
     */
    public String getRefererUril() {
        return refererUril;
    }

    /**
     * Sets refererUril.
     *
     * @param refererUril New value for refererUril.
     */
    public void setRefererUril(String refererUril) {
        this.refererUril = refererUril;
    }

    /**
     * Gets currPageUri.
     *
     * @return Value for currPageUri.
     */
    public String getCurrPageUri() {
        return currPageUri;
    }

    /**
     * Sets currPageUri.
     *
     * @param currPageUri New value for currPageUri.
     */
    public void setCurrPageUri(String currPageUri) {
        this.currPageUri = currPageUri;
    }

    /**
     * Gets pvType.
     *
     * @return Value for pvType.
     */
    public String getPvType() {
        return pvType;
    }

    /**
     * Sets pvType.
     *
     * @param pvType New value for pvType.
     */
    public void setPvType(String pvType) {
        this.pvType = pvType;
    }

    /**
     * Gets searchWord.
     *
     * @return Value for searchWord.
     */
    public String getSearchWord() {
        return searchWord;
    }

    /**
     * Sets searchWord.
     *
     * @param searchWord New value for searchWord.
     */
    public void setSearchWord(String searchWord) {
        this.searchWord = searchWord;
    }

    /**
     * Gets searchResultNum.
     *
     * @return Value for searchResultNum.
     */
    public String getSearchResultNum() {
        return searchResultNum;
    }

    /**
     * Sets searchResultNum.
     *
     * @param searchResultNum New value for searchResultNum.
     */
    public void setSearchResultNum(String searchResultNum) {
        this.searchResultNum = searchResultNum;
    }

    /**
     * Gets productCd.
     *
     * @return Value for productCd.
     */
    public String getProductCd() {
        return productCd;
    }

    /**
     * Sets productCd.
     *
     * @param productCd New value for productCd.
     */
    public void setProductCd(String productCd) {
        this.productCd = productCd;
    }

    /**
     * Gets productCatgL.
     *
     * @return Value for productCatgL.
     */
    public String getProductCatgL() {
        return productCatgL;
    }

    /**
     * Sets productCatgL.
     *
     * @param productCatgL New value for productCatgL.
     */
    public void setProductCatgL(String productCatgL) {
        this.productCatgL = productCatgL;
    }

    /**
     * Gets productCatgM.
     *
     * @return Value for productCatgM.
     */
    public String getProductCatgM() {
        return productCatgM;
    }

    /**
     * Sets productCatgM.
     *
     * @param productCatgM New value for productCatgM.
     */
    public void setProductCatgM(String productCatgM) {
        this.productCatgM = productCatgM;
    }

    /**
     * Gets productCatgS.
     *
     * @return Value for productCatgS.
     */
    public String getProductCatgS() {
        return productCatgS;
    }

    /**
     * Sets productCatgS.
     *
     * @param productCatgS New value for productCatgS.
     */
    public void setProductCatgS(String productCatgS) {
        this.productCatgS = productCatgS;
    }

    /**
     * Gets productBrandCd.
     *
     * @return Value for productBrandCd.
     */
    public String getProductBrandCd() {
        return productBrandCd;
    }

    /**
     * Sets productBrandCd.
     *
     * @param productBrandCd New value for productBrandCd.
     */
    public void setProductBrandCd(String productBrandCd) {
        this.productBrandCd = productBrandCd;
    }

    public String getBasketId() {
        return basketId;
    }

    public void setBasketId(String basketId) {
        this.basketId = basketId;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("LogBaseDetail [eventTimestamp=" + eventTimestamp);
        sb.append(", sessionId=" + sessionId);
        sb.append(", uuid=" + uuid);
        sb.append(", custId=" + custId);
        sb.append(", cookieId=" + cookieId);
        sb.append(", gender=" + gender);
        sb.append(", age=" + age);
        sb.append(", areaa=" + areaa);
        sb.append(", grade=" + grade);
        sb.append(", eventTypeCd=" + eventTypeCd);
        sb.append(", clickCd=" + clickCd);
        sb.append(", deviceType=" + deviceType);
        sb.append(", appWebType=" + appWebType);
        sb.append(", browserType=" + browserType);
        sb.append(", ipAddr=" + ipAddr);
        sb.append(", inboundChnlSrc=" + inboundChnlSrc);
        sb.append(", inboundChnlMedium=" + inboundChnlMedium);
        sb.append(", inboundChnlCampaign=" + inboundChnlCampaign);
        sb.append(", inboundChnlKeyword=" + inboundChnlKeyword);
        sb.append(", refererUril=" + refererUril);
        sb.append(", currPageUri=" + currPageUri);
        sb.append(", pvType=" + pvType);
        sb.append(", searchWord=" + searchWord);
        sb.append(", searchResultNum=" + searchResultNum);
        sb.append(", productCd=" + productCd);
        sb.append(", productCatgL=" + productCatgL);
        sb.append(", productCatgM=" + productCatgM);
        sb.append(", productCatgS=" + productCatgS);
        sb.append(", productBrandCd=" + productBrandCd);
        sb.append(", basketId=" + basketId);
        sb.append(", orderId=" + orderId);
        sb.append("]");
        return sb.toString();
    }
}

