/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.obzen.spark.application.batch.cjo.pojo;

import java.io.*;

/**
 * CJO_LOG_CORE definition.
 * <p>
 * Code generated by Apache Ignite Schema Import utility: 11/01/2017.
 */
public class CJO_LOG_CORE implements Serializable, Cloneable {
    /** */
    private static final long serialVersionUID = 0L;

    /**
     * Value for log_time.
     */
    private String log_time; 

    /**
     * Value for cust_age.
     */
    private String cust_age;

    /**
     * Value for app_cd.
     */
    private String app_cd;

    /**
     * Value for brand_cd.
     */
    private String brand_cd;

    /**
     * Value for intl_broad_tp.
     */
    private String intl_broad_tp;

    /**
     * Value for intl_tp.
     */
    private String intl_tp;

    /**
     * Value for browser_tp.
     */
    private String browser_tp;

    /**
     * Value for chn_cd.
     */
    private String chn_cd;

    /**
     * Value for click_depth1.
     */
    private String click_depth1;

    /**
     * Value for click_depth2.
     */
    private String click_depth2;

    /**
     * Value for click_depth3.
     */
    private String click_depth3;

    /**
     * Value for click_depth4.
     */
    private String click_depth4;

    /**
     * Value for click_depth5.
     */
    private String click_depth5;

    /**
     * Value for click_depth6.
     */
    private String click_depth6;

    /**
     * Value for click_depth6_seq.
     */
    private String click_depth6_seq;

    /**
     * Value for click_depth7.
     */
    private String click_depth7;

    /**
     * Value for click_depth7_seq.
     */
    private String click_depth7_seq;

    /**
     * Value for click_depth8.
     */
    private String click_depth8;

    /**
     * Value for click_depth8_seq.
     */
    private String click_depth8_seq;

    /**
     * Value for click_depth9.
     */

    private String click_depth9;

    /**
     * Value for click_depth9_seq.
     */
    private String click_depth9_seq;

    /**
     * Value for click_cd.
     */
    private String click_cd;

    /**
     * Value for cur_url_chn_tp.
     */
    private String cur_url_chn_tp;

    /**
     * Value for cur_file.
     */
    private String cur_file;

    /**
     * Value for cur_pg_info1.
     */
    private String cur_pg_info1;

    /**
     * Value for cur_pg_info2.
     */
    private String cur_pg_info2;

    /**
     * Value for cur_pg_info3.
     */
    private String cur_pg_info3;

    /**
     * Value for cur_pg_src_tp.
     */
    private String cur_pg_src_tp;

    /**
     * Value for cur_pg.
     */
    private String cur_pg;

    /**
     * Value for cur_url_domain.
     */
    private String cur_url_domain;

    /**
     * Value for cur_url_domain_tp.
     */
    private String cur_url_domain_tp;

    /**
     * Value for custom_pi.
     */
    private String custom_pi;

    /**
     * Value for date_yyyymmdd.
     */
    private String date_yyyymmdd;

    /**
     * Value for date_hour.
     */
    private String date_hour;

    /**
     * Value for date_mday.
     */
    private String date_mday;

    /**
     * Value for date_minute.
     */
    private String date_minute;

    /**
     * Value for date_month.
     */
    private String date_month;

    /**
     * Value for date_second.
     */
    private String date_second;

    /**
     * Value for date_wday.
     */
    private String date_wday;

    /**
     * Value for date_year.
     */
    private String date_year;

    /**
     * Value for empl_sale_item_fl.
     */
    private String empl_sale_item_fl;

    /**
     * Value for cust_empl_fl.
     */
    private String cust_empl_fl;

    /**
     * Value for event_cd.
     */
    private String event_cd;

    /**
     * Value for pg_load_time.
     */
    private String pg_load_time;

    /**
     * Value for cust_grade.
     */
    private String cust_grade;

    /**
     * Value for infl_cd.
     */
    private String infl_cd;

    /**
     * Value for infl_grp_cd.
     */
    private String infl_grp_cd;

    /**
     * Value for intl_pgm_cd.
     */
    private String intl_pgm_cd;

    /**
     * Value for log_tp.
     */
    private String log_tp;

    /**
     * Value for mobile_app_tp.
     */
    private String mobile_app_tp;

    /**
     * Value for md_cd.
     */
    private String md_cd;

    /**
     * Value for muuid.
     */
    private String muuid;

    /**
     * Value for ord_no.
     */
    private String ord_no;

    /**
     * Value for ord_prd_unit_cd.
     */
    private String ord_prd_unit_cd;

    /**
     * Value for os.
     */
    private String os;

    /**
     * Value for hometab_pic.
     */
    private String hometab_pic;

    /**
     * Value for ord_price.
     */
    private String ord_price;

    /**
     * Value for prd_cd.
     */
    private String prd_cd;

    /**
     * Value for prd_nm.
     */
    private String prd_nm;

    /**
     * Value for ord_prd_cnt.
     */
    private String ord_prd_cnt;

    /**
     * Value for ord_prd_nm.
     */
    private String ord_prd_nm;

    /**
     * Value for ref_url_chn_tp.
     */
    private String ref_url_chn_tp;

    /**
     * Value for ref_file.
     */
    private String ref_file;

    /**
     * Value for ref_pg_info1.
     */
    private String ref_pg_info1;

    /**
     * Value for ref_pg_info2.
     */
    private String ref_pg_info2;

    /**
     * Value for ref_pg_info3.
     */
    private String ref_pg_info3;

    /**
     * Value for ref_pg.
     */
    private String ref_pg;

    /**
     * Value for ref_url_domain.
     */
    private String ref_url_domain;

    /**
     * Value for ref_url_domain_tp.
     */
    private String ref_url_domain_tp;

    /**
     * Value for search_result.
     */
    private String search_result;

    /**
     * Value for search_word.
     */
    private String search_word;

    /**
     * Value for search_tp.
     */
    private String search_tp;

    /**
     * Value for mobile_app_service_nm.
     */
    private String mobile_app_service_nm;

    /**
     * Value for cust_gender.
     */
    private String cust_gender;

    /**
     * Value for shop_cd.
     */
    private String shop_cd;

    /**
     * Value for shop_nm.
     */
    private String shop_nm;

    /**
     * Value for sid.
     */
    private String sid;

    /**
     * Value for cust_spouse.
     */
    private String cust_spouse;

    /**
     * Value for std_cate_cd.
     */
    private String std_cate_cd;

    /**
     * Value for u_cookie.
     */
    private String u_cookie;

    /**
     * Value for udid.
     */
    private String udid;

    /**
     * Value for uid.
     */
    private String uid;

    /**
     * Value for cust_cd.
     */
    private String cust_cd;

    /**
     * Value for cust_id.
     */
    private String cust_id;

    /**
     * Value for useragent.
     */
    private String useragent;

    /**
     * Value for cust_visit_fl.
     */
    private String cust_visit_fl;

    /**
     * Value for visit_login_fl.
     */
    private String visit_login_fl;

    /**
     * Value for src_chn_tp.
     */
    private String src_chn_tp;

    /**
     * Value for ord_temp_no.
     */
    private String ord_temp_no;

    /**
     * Value for ord_prd_affili.
     */
    private String ord_prd_affili;

    /**
     * Value for infl_data.
     */
    private String infl_data;

    /**
     * Value for visit_pg_seq.
     */
    private String visit_pg_seq;

    /**
     * Value for cur_pg_nm.
     */
    private String cur_pg_nm;

    /**
     * Value for prd_tp.
     */
    private String prd_tp;

    /**
     * Value for vod_cd.
     */
    private String vod_cd;

    /**
     * Value for pgm_cd.
     */
    private String pgm_cd;

    /**
     * Value for partner_cd.
     */
    private String partner_cd;

    /**
     * Value for web_cate_g_cd.
     */
    private String web_cate_g_cd;

    /**
     * Value for web_cate_l_cd.
     */
    private String web_cate_l_cd;

    /**
     * Value for web_cate_m_cd.
     */
    private String web_cate_m_cd;

    /**
     * Value for web_cate_s_cd.
     */
    private String web_cate_s_cd;

    /**
     * Value for host.
     */
    private String host;

    /**
     * Value for sourcetype.
     */
    private String sourcetype;

    /**
     * Value for prd_seq.
     */
    private String prd_seq;

    
    /**
     * Value for comm_cd. (커뮤니티번호 추가)
     * 2018.03.09
     */
    private String comm_cd; 
    
    /**
     * Value for bbs_cd. (게시불번호 추가)
     * 2018.03.09
     */
    private String bbs_cd;
    
    /**
     * Value for ord_sht_tp. (주문서타입 추가)
     * 2018.11.28
     */
    private String ord_sht_tp;
    

	/**
     * Empty constructor.
     */
    public CJO_LOG_CORE() {
        // No-op.
    }

    /**
     * Full constructor.
     */
    public CJO_LOG_CORE(
            String log_time,
            String cust_age,
            String app_cd,
            String brand_cd,
            String intl_broad_tp,
            String intl_tp,
            String browser_tp,
            String chn_cd,
            String click_depth1,
            String click_depth2,
            String click_depth3,
            String click_depth4,
            String click_depth5,
            String click_depth6,
            String click_depth6_seq,
            String click_depth7,
            String click_depth7_seq,
            String click_depth8,
            String click_depth8_seq,
            String click_depth9,
            String click_depth9_seq,
            String click_cd,
            String cur_url_chn_tp,
            String cur_file,
            String cur_pg_info1,
            String cur_pg_info2,
            String cur_pg_info3,
            String cur_pg_src_tp,
            String cur_pg,
            String cur_url_domain,
            String cur_url_domain_tp,
            String custom_pi,
            String date_yyyymmdd,
            String date_hour,
            String date_mday,
            String date_minute,
            String date_month,
            String date_second,
            String date_wday,
            String date_year,
            String empl_sale_item_fl,
            String cust_empl_fl,
            String event_cd,
            String pg_load_time,
            String cust_grade,
            String infl_cd,
            String infl_grp_cd,
            String intl_pgm_cd,
            String log_tp,
            String mobile_app_tp,
            String md_cd,
            String muuid,
            String ord_no,
            String ord_prd_unit_cd,
            String os,
            String hometab_pic,
            String ord_price,
            String prd_cd,
            String prd_nm,
            String ord_prd_cnt,
            String ord_prd_nm,
            String ref_url_chn_tp,
            String ref_file,
            String ref_pg_info1,
            String ref_pg_info2,
            String ref_pg_info3,
            String ref_pg,
            String ref_url_domain,
            String ref_url_domain_tp,
            String search_result,
            String search_word,
            String search_tp,
            String mobile_app_service_nm,
            String cust_gender,
            String shop_cd,
            String shop_nm,
            String sid,
            String cust_spouse,
            String std_cate_cd,
            String u_cookie,
            String udid,
            String uid,
            String cust_cd,
            String cust_id,
            String useragent,
            String cust_visit_fl,
            String visit_login_fl,
            String src_chn_tp,
            String ord_temp_no,
            String ord_prd_affili,
            String infl_data,
            String visit_pg_seq,
            String cur_pg_nm,
            String prd_tp,
            String vod_cd,
            String pgm_cd,
            String partner_cd,
            String web_cate_g_cd,
            String web_cate_l_cd,
            String web_cate_m_cd,
            String web_cate_s_cd,
            String host,
            String sourcetype,
            String prd_seq            
          ,  String comm_cd /* 2018.03.09 커뮤니티번호 추가*/
          ,  String bbs_cd /* 2018.03.09 게시불번호 추가*/
          ,  String ord_sht_tp /* 2018.11.28 주문서타입 추가*/

    ) {
        this.log_time = log_time;
        this.cust_age = cust_age;
        this.app_cd = app_cd;
        this.brand_cd = brand_cd;
        this.intl_broad_tp = intl_broad_tp;
        this.intl_tp = intl_tp;
        this.browser_tp = browser_tp;
        this.chn_cd = chn_cd;
        this.click_depth1 = click_depth1;
        this.click_depth2 = click_depth2;
        this.click_depth3 = click_depth3;
        this.click_depth4 = click_depth4;
        this.click_depth5 = click_depth5;
        this.click_depth6 = click_depth6;
        this.click_depth6_seq = click_depth6_seq;
        this.click_depth7 = click_depth7;
        this.click_depth7_seq = click_depth7_seq;
        this.click_depth8 = click_depth8;
        this.click_depth8_seq = click_depth8_seq;
        this.click_depth9 = click_depth9;
        this.click_depth9_seq = click_depth9_seq;
        this.click_cd = click_cd;
        this.cur_url_chn_tp = cur_url_chn_tp;
        this.cur_file = cur_file;
        this.cur_pg_info1 = cur_pg_info1;
        this.cur_pg_info2 = cur_pg_info2;
        this.cur_pg_info3 = cur_pg_info3;
        this.cur_pg_src_tp = cur_pg_src_tp;
        this.cur_pg = cur_pg;
        this.cur_url_domain = cur_url_domain;
        this.cur_url_domain_tp = cur_url_domain_tp;
        this.custom_pi = custom_pi;
        this.date_yyyymmdd = date_yyyymmdd;
        this.date_hour = date_hour;
        this.date_mday = date_mday;
        this.date_minute = date_minute;
        this.date_month = date_month;
        this.date_second = date_second;
        this.date_wday = date_wday;
        this.date_year = date_year;
        this.empl_sale_item_fl = empl_sale_item_fl;
        this.cust_empl_fl = cust_empl_fl;
        this.event_cd = event_cd;
        this.pg_load_time = pg_load_time;
        this.cust_grade = cust_grade;
        this.infl_cd = infl_cd;
        this.infl_grp_cd = infl_grp_cd;
        this.intl_pgm_cd = intl_pgm_cd;
        this.log_tp = log_tp;
        this.mobile_app_tp = mobile_app_tp;
        this.md_cd = md_cd;
        this.muuid = muuid;
        this.ord_no = ord_no;
        this.ord_prd_unit_cd = ord_prd_unit_cd;
        this.os = os;
        this.hometab_pic = hometab_pic;
        this.ord_price = ord_price;
        this.prd_cd = prd_cd;
        this.prd_nm = prd_nm;
        this.ord_prd_cnt = ord_prd_cnt;
        this.ord_prd_nm = ord_prd_nm;
        this.ref_url_chn_tp = ref_url_chn_tp;
        this.ref_file = ref_file;
        this.ref_pg_info1 = ref_pg_info1;
        this.ref_pg_info2 = ref_pg_info2;
        this.ref_pg_info3 = ref_pg_info3;
        this.ref_pg = ref_pg;
        this.ref_url_domain = ref_url_domain;
        this.ref_url_domain_tp = ref_url_domain_tp;
        this.search_result = search_result;
        this.search_word = search_word;
        this.search_tp = search_tp;
        this.mobile_app_service_nm = mobile_app_service_nm;
        this.cust_gender = cust_gender;
        this.shop_cd = shop_cd;
        this.shop_nm = shop_nm;
        this.sid = sid;
        this.cust_spouse = cust_spouse;
        this.std_cate_cd = std_cate_cd;
        this.u_cookie = u_cookie;
        this.udid = udid;
        this.uid = uid;
        this.cust_cd = cust_cd;
        this.cust_id = cust_id;
        this.useragent = useragent;
        this.cust_visit_fl = cust_visit_fl;
        this.visit_login_fl = visit_login_fl;
        this.src_chn_tp = src_chn_tp;
        this.ord_temp_no = ord_temp_no;
        this.ord_prd_affili = ord_prd_affili;
        this.infl_data = infl_data;
        this.visit_pg_seq = visit_pg_seq;
        this.cur_pg_nm = cur_pg_nm;
        this.prd_tp = prd_tp;
        this.vod_cd = vod_cd;
        this.pgm_cd = pgm_cd;
        this.partner_cd = partner_cd;
        this.web_cate_g_cd = web_cate_g_cd;
        this.web_cate_l_cd = web_cate_l_cd;
        this.web_cate_m_cd = web_cate_m_cd;
        this.web_cate_s_cd = web_cate_s_cd;
        this.host = host;
        this.sourcetype = sourcetype;
        this.prd_seq = prd_seq;        
        this.comm_cd = comm_cd; /* 2018.03.09 커뮤니티번호 추가*/
        this.bbs_cd = bbs_cd; /* 2018.03.09 게시불번호 추가*/
        this.ord_sht_tp = ord_sht_tp; /* 2018.11.28 주문서타입 추가*/
    }

    /**
     * Gets log_time.
     *
     * @return Value for log_time.
     */
    public String getLog_time() {
        return log_time;
    }

    /**
     * Sets log_time.
     *
     * @param log_time New value for log_time.
     */
    public void setLog_time(String log_time) {
        this.log_time = log_time;
    }

    /**
     * Gets cust_age.
     *
     * @return Value for cust_age.
     */
    public String getCust_age() {
        return cust_age;
    }

    /**
     * Sets cust_age.
     *
     * @param cust_age New value for cust_age.
     */
    public void setCust_age(String cust_age) {
        this.cust_age = cust_age;
    }

    /**
     * Gets app_cd.
     *
     * @return Value for app_cd.
     */
    public String getApp_cd() {
        return app_cd;
    }

    /**
     * Sets app_cd.
     *
     * @param app_cd New value for app_cd.
     */
    public void setApp_cd(String app_cd) {
        this.app_cd = app_cd;
    }

    /**
     * Gets brand_cd.
     *
     * @return Value for brand_cd.
     */
    public String getBrand_cd() {
        return brand_cd;
    }

    /**
     * Sets brand_cd.
     *
     * @param brand_cd New value for brand_cd.
     */
    public void setBrand_cd(String brand_cd) {
        this.brand_cd = brand_cd;
    }

    /**
     * Gets intl_broad_tp.
     *
     * @return Value for intl_broad_tp.
     */
    public String getIntl_broad_tp() {
        return intl_broad_tp;
    }

    /**
     * Sets intl_broad_tp.
     *
     * @param intl_broad_tp New value for intl_broad_tp.
     */
    public void setIntl_broad_tp(String intl_broad_tp) {
        this.intl_broad_tp = intl_broad_tp;
    }

    /**
     * Gets intl_tp.
     *
     * @return Value for intl_tp.
     */
    public String getIntl_tp() {
        return intl_tp;
    }

    /**
     * Sets intl_tp.
     *
     * @param intl_tp New value for intl_tp.
     */
    public void setIntl_tp(String intl_tp) {
        this.intl_tp = intl_tp;
    }

    /**
     * Gets browser_tp.
     *
     * @return Value for browser_tp.
     */
    public String getBrowser_tp() {
        return browser_tp;
    }

    /**
     * Sets browser_tp.
     *
     * @param browser_tp New value for browser_tp.
     */
    public void setBrowser_tp(String browser_tp) {
        this.browser_tp = browser_tp;
    }

    /**
     * Gets chn_cd.
     *
     * @return Value for chn_cd.
     */
    public String getChn_cd() {
        return chn_cd;
    }

    /**
     * Sets chn_cd.
     *
     * @param chn_cd New value for chn_cd.
     */
    public void setChn_cd(String chn_cd) {
        this.chn_cd = chn_cd;
    }

    /**
     * Gets click_depth1.
     *
     * @return Value for click_depth1.
     */
    public String getClick_depth1() {
        return click_depth1;
    }

    /**
     * Sets click_depth1.
     *
     * @param click_depth1 New value for click_depth1.
     */
    public void setClick_depth1(String click_depth1) {
        this.click_depth1 = click_depth1;
    }

    /**
     * Gets click_depth2.
     *
     * @return Value for click_depth2.
     */
    public String getClick_depth2() {
        return click_depth2;
    }

    /**
     * Sets click_depth2.
     *
     * @param click_depth2 New value for click_depth2.
     */
    public void setClick_depth2(String click_depth2) {
        this.click_depth2 = click_depth2;
    }

    /**
     * Gets click_depth3.
     *
     * @return Value for click_depth3.
     */
    public String getClick_depth3() {
        return click_depth3;
    }

    /**
     * Sets click_depth3.
     *
     * @param click_depth3 New value for click_depth3.
     */
    public void setClick_depth3(String click_depth3) {
        this.click_depth3 = click_depth3;
    }

    /**
     * Gets click_depth4.
     *
     * @return Value for click_depth4.
     */
    public String getClick_depth4() {
        return click_depth4;
    }

    /**
     * Sets click_depth4.
     *
     * @param click_depth4 New value for click_depth4.
     */
    public void setClick_depth4(String click_depth4) {
        this.click_depth4 = click_depth4;
    }

    /**
     * Gets click_depth5.
     *
     * @return Value for click_depth5.
     */
    public String getClick_depth5() {
        return click_depth5;
    }

    /**
     * Sets click_depth5.
     *
     * @param click_depth5 New value for click_depth5.
     */
    public void setClick_depth5(String click_depth5) {
        this.click_depth5 = click_depth5;
    }

    /**
     * Gets click_depth6.
     *
     * @return Value for click_depth6.
     */
    public String getClick_depth6() {
        return click_depth6;
    }

    /**
     * Sets click_depth6.
     *
     * @param click_depth6 New value for click_depth6.
     */
    public void setClick_depth6(String click_depth6) {
        this.click_depth6 = click_depth6;
    }

    /**
     * Gets click_depth6_seq.
     *
     * @return Value for click_depth6_seq.
     */
    public String getClick_depth6_seq() {
        return click_depth6_seq;
    }

    /**
     * Sets click_depth6_seq.
     *
     * @param click_depth6_seq New value for click_depth6_seq.
     */
    public void setClick_depth6_seq(String click_depth6_seq) {
        this.click_depth6_seq = click_depth6_seq;
    }

    /**
     * Gets click_depth7.
     *
     * @return Value for click_depth7.
     */
    public String getClick_depth7() {
        return click_depth7;
    }

    /**
     * Sets click_depth7.
     *
     * @param click_depth7 New value for click_depth7.
     */
    public void setClick_depth7(String click_depth7) {
        this.click_depth7 = click_depth7;
    }

    /**
     * Gets click_depth7_seq.
     *
     * @return Value for click_depth7_seq.
     */
    public String getClick_depth7_seq() {
        return click_depth7_seq;
    }

    /**
     * Sets click_depth7_seq.
     *
     * @param click_depth7_seq New value for click_depth7_seq.
     */
    public void setClick_depth7_seq(String click_depth7_seq) {
        this.click_depth7_seq = click_depth7_seq;
    }

    /**
     * Gets click_depth8.
     *
     * @return Value for click_depth8.
     */
    public String getClick_depth8() {
        return click_depth8;
    }

    /**
     * Sets click_depth8.
     *
     * @param click_depth8 New value for click_depth8.
     */
    public void setClick_depth8(String click_depth8) {
        this.click_depth8 = click_depth8;
    }

    /**
     * Gets click_depth8_seq.
     *
     * @return Value for click_depth8_seq.
     */
    public String getClick_depth8_seq() {
        return click_depth8_seq;
    }

    /**
     * Sets click_depth8_seq.
     *
     * @param click_depth8_seq New value for click_depth8_seq.
     */
    public void setClick_depth8_seq(String click_depth8_seq) {
        this.click_depth8_seq = click_depth8_seq;
    }

    /**
     * Gets click_depth9.
     *
     * @return Value for click_depth9.
     */
    public String getClick_depth9() {
        return click_depth9;
    }

    /**
     * Sets click_depth9.
     *
     * @param click_depth9 New value for click_depth9.
     */
    public void setClick_depth9(String click_depth9) {
        this.click_depth9 = click_depth9;
    }

    /**
     * Gets click_depth9_seq.
     *
     * @return Value for click_depth9_seq.
     */
    public String getClick_depth9_seq() {
        return click_depth9_seq;
    }

    /**
     * Sets click_depth9_seq.
     *
     * @param click_depth9_seq New value for click_depth9_seq.
     */
    public void setClick_depth9_seq(String click_depth9_seq) {
        this.click_depth9_seq = click_depth9_seq;
    }

    /**
     * Gets click_cd.
     *
     * @return Value for click_cd.
     */
    public String getClick_cd() {
        return click_cd;
    }

    /**
     * Sets click_cd.
     *
     * @param click_cd New value for click_cd.
     */
    public void setClick_cd(String click_cd) {
        this.click_cd = click_cd;
    }

    /**
     * Gets cur_url_chn_tp.
     *
     * @return Value for cur_url_chn_tp.
     */
    public String getCur_url_chn_tp() {
        return cur_url_chn_tp;
    }

    /**
     * Sets cur_url_chn_tp.
     *
     * @param cur_url_chn_tp New value for cur_url_chn_tp.
     */
    public void setCur_url_chn_tp(String cur_url_chn_tp) {
        this.cur_url_chn_tp = cur_url_chn_tp;
    }

    /**
     * Gets cur_file.
     *
     * @return Value for cur_file.
     */
    public String getCur_file() {
        return cur_file;
    }

    /**
     * Sets cur_file.
     *
     * @param cur_file New value for cur_file.
     */
    public void setCur_file(String cur_file) {
        this.cur_file = cur_file;
    }

    /**
     * Gets cur_pg_info1.
     *
     * @return Value for cur_pg_info1.
     */
    public String getCur_pg_info1() {
        return cur_pg_info1;
    }

    /**
     * Sets cur_pg_info1.
     *
     * @param cur_pg_info1 New value for cur_pg_info1.
     */
    public void setCur_pg_info1(String cur_pg_info1) {
        this.cur_pg_info1 = cur_pg_info1;
    }

    /**
     * Gets cur_pg_info2.
     *
     * @return Value for cur_pg_info2.
     */
    public String getCur_pg_info2() {
        return cur_pg_info2;
    }

    /**
     * Sets cur_pg_info2.
     *
     * @param cur_pg_info2 New value for cur_pg_info2.
     */
    public void setCur_pg_info2(String cur_pg_info2) {
        this.cur_pg_info2 = cur_pg_info2;
    }

    /**
     * Gets cur_pg_info3.
     *
     * @return Value for cur_pg_info3.
     */
    public String getCur_pg_info3() {
        return cur_pg_info3;
    }

    /**
     * Sets cur_pg_info3.
     *
     * @param cur_pg_info3 New value for cur_pg_info3.
     */
    public void setCur_pg_info3(String cur_pg_info3) {
        this.cur_pg_info3 = cur_pg_info3;
    }

    /**
     * Gets cur_pg_src_tp.
     *
     * @return Value for cur_pg_src_tp.
     */
    public String getCur_pg_src_tp() {
        return cur_pg_src_tp;
    }

    /**
     * Sets cur_pg_src_tp.
     *
     * @param cur_pg_src_tp New value for cur_pg_src_tp.
     */
    public void setCur_pg_src_tp(String cur_pg_src_tp) {
        this.cur_pg_src_tp = cur_pg_src_tp;
    }

    /**
     * Gets cur_pg.
     *
     * @return Value for cur_pg.
     */
    public String getCur_pg() {
        return cur_pg;
    }

    /**
     * Sets cur_pg.
     *
     * @param cur_pg New value for cur_pg.
     */
    public void setCur_pg(String cur_pg) {
        this.cur_pg = cur_pg;
    }

    /**
     * Gets cur_url_domain.
     *
     * @return Value for cur_url_domain.
     */
    public String getCur_url_domain() {
        return cur_url_domain;
    }

    /**
     * Sets cur_url_domain.
     *
     * @param cur_url_domain New value for cur_url_domain.
     */
    public void setCur_url_domain(String cur_url_domain) {
        this.cur_url_domain = cur_url_domain;
    }

    /**
     * Gets cur_url_domain_tp.
     *
     * @return Value for cur_url_domain_tp.
     */
    public String getCur_url_domain_tp() {
        return cur_url_domain_tp;
    }

    /**
     * Sets cur_url_domain_tp.
     *
     * @param cur_url_domain_tp New value for cur_url_domain_tp.
     */
    public void setCur_url_domain_tp(String cur_url_domain_tp) {
        this.cur_url_domain_tp = cur_url_domain_tp;
    }

    /**
     * Gets custom_pi.
     *
     * @return Value for custom_pi.
     */
    public String getCustom_pi() {
        return custom_pi;
    }

    /**
     * Sets custom_pi.
     *
     * @param custom_pi New value for custom_pi.
     */
    public void setCustom_pi(String custom_pi) {
        this.custom_pi = custom_pi;
    }

    /**
     * Gets date_yyyymmdd.
     *
     * @return Value for date_yyyymmdd.
     */
    public String getDate_yyyymmdd() {
        return date_yyyymmdd;
    }

    /**
     * Gets date_yyyymmdd.
     *
     * @return Value for date_yyyymmdd.
     */
    public void setDate_yyyymmdd(String date_yyyymmdd) {
        this.date_yyyymmdd = date_yyyymmdd;
    }

    /**
     * Gets date_hour.
     *
     * @return Value for date_hour.
     */
    public String getDate_hour() {
        return date_hour;
    }

    /**
     * Sets date_hour.
     *
     * @param date_hour New value for date_hour.
     */
    public void setDate_hour(String date_hour) {
        this.date_hour = date_hour;
    }

    /**
     * Gets date_mday.
     *
     * @return Value for date_mday.
     */
    public String getDate_mday() {
        return date_mday;
    }

    /**
     * Sets date_mday.
     *
     * @param date_mday New value for date_mday.
     */
    public void setDate_mday(String date_mday) {
        this.date_mday = date_mday;
    }

    /**
     * Gets date_minute.
     *
     * @return Value for date_minute.
     */
    public String getDate_minute() {
        return date_minute;
    }

    /**
     * Sets date_minute.
     *
     * @param date_minute New value for date_minute.
     */
    public void setDate_minute(String date_minute) {
        this.date_minute = date_minute;
    }

    /**
     * Gets date_month.
     *
     * @return Value for date_month.
     */
    public String getDate_month() {
        return date_month;
    }

    /**
     * Sets date_month.
     *
     * @param date_month New value for date_month.
     */
    public void setDate_month(String date_month) {
        this.date_month = date_month;
    }

    /**
     * Gets date_second.
     *
     * @return Value for date_second.
     */
    public String getDate_second() {
        return date_second;
    }

    /**
     * Sets date_second.
     *
     * @param date_second New value for date_second.
     */
    public void setDate_second(String date_second) {
        this.date_second = date_second;
    }

    /**
     * Gets date_wday.
     *
     * @return Value for date_wday.
     */
    public String getDate_wday() {
        return date_wday;
    }

    /**
     * Sets date_wday.
     *
     * @param date_wday New value for date_wday.
     */
    public void setDate_wday(String date_wday) {
        this.date_wday = date_wday;
    }

    /**
     * Gets date_year.
     *
     * @return Value for date_year.
     */
    public String getDate_year() {
        return date_year;
    }

    /**
     * Sets date_year.
     *
     * @param date_year New value for date_year.
     */
    public void setDate_year(String date_year) {
        this.date_year = date_year;
    }

    /**
     * Gets empl_sale_item_fl.
     *
     * @return Value for empl_sale_item_fl.
     */
    public String getEmpl_sale_item_fl() {
        return empl_sale_item_fl;
    }

    /**
     * Sets empl_sale_item_fl.
     *
     * @param empl_sale_item_fl New value for empl_sale_item_fl.
     */
    public void setEmpl_sale_item_fl(String empl_sale_item_fl) {
        this.empl_sale_item_fl = empl_sale_item_fl;
    }

    /**
     * Gets cust_empl_fl.
     *
     * @return Value for cust_empl_fl.
     */
    public String getCust_empl_fl() {
        return cust_empl_fl;
    }

    /**
     * Sets cust_empl_fl.
     *
     * @param cust_empl_fl New value for cust_empl_fl.
     */
    public void setCust_empl_fl(String cust_empl_fl) {
        this.cust_empl_fl = cust_empl_fl;
    }

    /**
     * Gets event_cd.
     *
     * @return Value for event_cd.
     */
    public String getEvent_cd() {
        return event_cd;
    }

    /**
     * Sets event_cd.
     *
     * @param event_cd New value for event_cd.
     */
    public void setEvent_cd(String event_cd) {
        this.event_cd = event_cd;
    }

    /**
     * Gets pg_load_time.
     *
     * @return Value for pg_load_time.
     */
    public String getPg_load_time() {
        return pg_load_time;
    }

    /**
     * Sets pg_load_time.
     *
     * @param pg_load_time New value for pg_load_time.
     */
    public void setPg_load_time(String pg_load_time) {
        this.pg_load_time = pg_load_time;
    }

    /**
     * Gets cust_grade.
     *
     * @return Value for cust_grade.
     */
    public String getCust_grade() {
        return cust_grade;
    }

    /**
     * Sets cust_grade.
     *
     * @param cust_grade New value for cust_grade.
     */
    public void setCust_grade(String cust_grade) {
        this.cust_grade = cust_grade;
    }

    /**
     * Gets infl_cd.
     *
     * @return Value for infl_cd.
     */
    public String getInfl_cd() {
        return infl_cd;
    }

    /**
     * Sets infl_cd.
     *
     * @param infl_cd New value for infl_cd.
     */
    public void setInfl_cd(String infl_cd) {
        this.infl_cd = infl_cd;
    }

    /**
     * Gets infl_grp_cd.
     *
     * @return Value for infl_grp_cd.
     */
    public String getInfl_grp_cd() {
        return infl_grp_cd;
    }

    /**
     * Sets infl_grp_cd.
     *
     * @param infl_grp_cd New value for infl_grp_cd.
     */
    public void setInfl_grp_cd(String infl_grp_cd) {
        this.infl_grp_cd = infl_grp_cd;
    }

    /**
     * Gets intl_pgm_cd.
     *
     * @return Value for intl_pgm_cd.
     */
    public String getIntl_pgm_cd() {
        return intl_pgm_cd;
    }

    /**
     * Sets intl_pgm_cd.
     *
     * @param intl_pgm_cd New value for intl_pgm_cd.
     */
    public void setIntl_pgm_cd(String intl_pgm_cd) {
        this.intl_pgm_cd = intl_pgm_cd;
    }

    /**
     * Gets log_tp.
     *
     * @return Value for log_tp.
     */
    public String getLog_tp() {
        return log_tp;
    }

    /**
     * Sets log_tp.
     *
     * @param log_tp New value for log_tp.
     */
    public void setLog_tp(String log_tp) {
        this.log_tp = log_tp;
    }

    /**
     * Gets mobile_app_tp.
     *
     * @return Value for mobile_app_tp.
     */
    public String getMobile_app_tp() {
        return mobile_app_tp;
    }

    /**
     * Sets mobile_app_tp.
     *
     * @param mobile_app_tp New value for mobile_app_tp.
     */
    public void setMobile_app_tp(String mobile_app_tp) {
        this.mobile_app_tp = mobile_app_tp;
    }

    /**
     * Gets md_cd.
     *
     * @return Value for md_cd.
     */
    public String getMd_cd() {
        return md_cd;
    }

    /**
     * Sets md_cd.
     *
     * @param md_cd New value for md_cd.
     */
    public void setMd_cd(String md_cd) {
        this.md_cd = md_cd;
    }

    /**
     * Gets muuid.
     *
     * @return Value for muuid.
     */
    public String getMuuid() {
        return muuid;
    }

    /**
     * Sets muuid.
     *
     * @param muuid New value for muuid.
     */
    public void setMuuid(String muuid) {
        this.muuid = muuid;
    }

    /**
     * Gets ord_no.
     *
     * @return Value for ord_no.
     */
    public String getOrd_no() {
        return ord_no;
    }

    /**
     * Sets ord_no.
     *
     * @param ord_no New value for ord_no.
     */
    public void setOrd_no(String ord_no) {
        this.ord_no = ord_no;
    }

    /**
     * Gets ord_prd_unit_cd.
     *
     * @return Value for ord_prd_unit_cd.
     */
    public String getOrd_prd_unit_cd() {
        return ord_prd_unit_cd;
    }

    /**
     * Sets ord_prd_unit_cd.
     *
     * @param ord_prd_unit_cd New value for ord_prd_unit_cd.
     */
    public void setOrd_prd_unit_cd(String ord_prd_unit_cd) {
        this.ord_prd_unit_cd = ord_prd_unit_cd;
    }

    /**
     * Gets os.
     *
     * @return Value for os.
     */
    public String getOs() {
        return os;
    }

    /**
     * Sets os.
     *
     * @param os New value for os.
     */
    public void setOs(String os) {
        this.os = os;
    }

    /**
     * Gets hometab_pic.
     *
     * @return Value for hometab_pic.
     */
    public String getHometab_pic() {
        return hometab_pic;
    }

    /**
     * Sets hometab_pic.
     *
     * @param hometab_pic New value for hometab_pic.
     */
    public void setHometab_pic(String hometab_pic) {
        this.hometab_pic = hometab_pic;
    }

    /**
     * Gets ord_price.
     *
     * @return Value for ord_price.
     */
    public String getOrd_price() {
        return ord_price;
    }

    /**
     * Sets ord_price.
     *
     * @param ord_price New value for ord_price.
     */
    public void setOrd_price(String ord_price) {
        this.ord_price = ord_price;
    }

    /**
     * Gets prd_cd.
     *
     * @return Value for prd_cd.
     */
    public String getPrd_cd() {
        return prd_cd;
    }

    /**
     * Sets prd_cd.
     *
     * @param prd_cd New value for prd_cd.
     */
    public void setPrd_cd(String prd_cd) {
        this.prd_cd = prd_cd;
    }

    /**
     * Gets prd_nm.
     *
     * @return Value for prd_nm.
     */
    public String getPrd_nm() {
        return prd_nm;
    }

    /**
     * Sets prd_nm.
     *
     * @param prd_nm New value for prd_nm.
     */
    public void setPrd_nm(String prd_nm) {
        this.prd_nm = prd_nm;
    }

    /**
     * Gets ord_prd_cnt.
     *
     * @return Value for ord_prd_cnt.
     */
    public String getOrd_prd_cnt() {
        return ord_prd_cnt;
    }

    /**
     * Sets ord_prd_cnt.
     *
     * @param ord_prd_cnt New value for ord_prd_cnt.
     */
    public void setOrd_prd_cnt(String ord_prd_cnt) {
        this.ord_prd_cnt = ord_prd_cnt;
    }

    /**
     * Gets ord_prd_nm.
     *
     * @return Value for ord_prd_nm.
     */
    public String getOrd_prd_nm() {
        return ord_prd_nm;
    }

    /**
     * Sets ord_prd_nm.
     *
     * @param ord_prd_nm New value for ord_prd_nm.
     */
    public void setOrd_prd_nm(String ord_prd_nm) {
        this.ord_prd_nm = ord_prd_nm;
    }

    /**
     * Gets ref_url_chn_tp.
     *
     * @return Value for ref_url_chn_tp.
     */
    public String getRef_url_chn_tp() {
        return ref_url_chn_tp;
    }

    /**
     * Sets ref_url_chn_tp.
     *
     * @param ref_url_chn_tp New value for ref_url_chn_tp.
     */
    public void setRef_url_chn_tp(String ref_url_chn_tp) {
        this.ref_url_chn_tp = ref_url_chn_tp;
    }

    /**
     * Gets ref_file.
     *
     * @return Value for ref_file.
     */
    public String getRef_file() {
        return ref_file;
    }

    /**
     * Sets ref_file.
     *
     * @param ref_file New value for ref_file.
     */
    public void setRef_file(String ref_file) {
        this.ref_file = ref_file;
    }

    /**
     * Gets ref_pg_info1.
     *
     * @return Value for ref_pg_info1.
     */
    public String getRef_pg_info1() {
        return ref_pg_info1;
    }

    /**
     * Sets ref_pg_info1.
     *
     * @param ref_pg_info1 New value for ref_pg_info1.
     */
    public void setRef_pg_info1(String ref_pg_info1) {
        this.ref_pg_info1 = ref_pg_info1;
    }

    /**
     * Gets ref_pg_info2.
     *
     * @return Value for ref_pg_info2.
     */
    public String getRef_pg_info2() {
        return ref_pg_info2;
    }

    /**
     * Sets ref_pg_info2.
     *
     * @param ref_pg_info2 New value for ref_pg_info2.
     */
    public void setRef_pg_info2(String ref_pg_info2) {
        this.ref_pg_info2 = ref_pg_info2;
    }

    /**
     * Gets ref_pg_info3.
     *
     * @return Value for ref_pg_info3.
     */
    public String getRef_pg_info3() {
        return ref_pg_info3;
    }

    /**
     * Sets ref_pg_info3.
     *
     * @param ref_pg_info3 New value for ref_pg_info3.
     */
    public void setRef_pg_info3(String ref_pg_info3) {
        this.ref_pg_info3 = ref_pg_info3;
    }

    /**
     * Gets ref_pg.
     *
     * @return Value for ref_pg.
     */
    public String getRef_pg() {
        return ref_pg;
    }

    /**
     * Sets ref_pg.
     *
     * @param ref_pg New value for ref_pg.
     */
    public void setRef_pg(String ref_pg) {
        this.ref_pg = ref_pg;
    }

    /**
     * Gets ref_url_domain.
     *
     * @return Value for ref_url_domain.
     */
    public String getRef_url_domain() {
        return ref_url_domain;
    }

    /**
     * Sets ref_url_domain.
     *
     * @param ref_url_domain New value for ref_url_domain.
     */
    public void setRef_url_domain(String ref_url_domain) {
        this.ref_url_domain = ref_url_domain;
    }

    /**
     * Gets ref_url_domain_tp.
     *
     * @return Value for ref_url_domain_tp.
     */
    public String getRef_url_domain_tp() {
        return ref_url_domain_tp;
    }

    /**
     * Sets ref_url_domain_tp.
     *
     * @param ref_url_domain_tp New value for ref_url_domain_tp.
     */
    public void setRef_url_domain_tp(String ref_url_domain_tp) {
        this.ref_url_domain_tp = ref_url_domain_tp;
    }

    /**
     * Gets search_result.
     *
     * @return Value for search_result.
     */
    public String getSearch_result() {
        return search_result;
    }

    /**
     * Sets search_result.
     *
     * @param search_result New value for search_result.
     */
    public void setSearch_result(String search_result) {
        this.search_result = search_result;
    }

    /**
     * Gets search_word.
     *
     * @return Value for search_word.
     */
    public String getSearch_word() {
        return search_word;
    }

    /**
     * Sets search_word.
     *
     * @param search_word New value for search_word.
     */
    public void setSearch_word(String search_word) {
        this.search_word = search_word;
    }

    /**
     * Gets search_tp.
     *
     * @return Value for search_tp.
     */
    public String getSearch_tp() {
        return search_tp;
    }

    /**
     * Sets search_tp.
     *
     * @param search_tp New value for search_tp.
     */
    public void setSearch_tp(String search_tp) {
        this.search_tp = search_tp;
    }

    /**
     * Gets mobile_app_service_nm.
     *
     * @return Value for mobile_app_service_nm.
     */
    public String getMobile_app_service_nm() {
        return mobile_app_service_nm;
    }

    /**
     * Sets mobile_app_service_nm.
     *
     * @param mobile_app_service_nm New value for mobile_app_service_nm.
     */
    public void setMobile_app_service_nm(String mobile_app_service_nm) {
        this.mobile_app_service_nm = mobile_app_service_nm;
    }

    /**
     * Gets cust_gender.
     *
     * @return Value for cust_gender.
     */
    public String getCust_gender() {
        return cust_gender;
    }

    /**
     * Sets cust_gender.
     *
     * @param cust_gender New value for cust_gender.
     */
    public void setCust_gender(String cust_gender) {
        this.cust_gender = cust_gender;
    }

    /**
     * Gets shop_cd.
     *
     * @return Value for shop_cd.
     */
    public String getShop_cd() {
        return shop_cd;
    }

    /**
     * Sets shop_cd.
     *
     * @param shop_cd New value for shop_cd.
     */
    public void setShop_cd(String shop_cd) {
        this.shop_cd = shop_cd;
    }

    /**
     * Gets shop_nm.
     *
     * @return Value for shop_nm.
     */
    public String getShop_nm() {
        return shop_nm;
    }

    /**
     * Sets shop_nm.
     *
     * @param shop_nm New value for shop_nm.
     */
    public void setShop_nm(String shop_nm) {
        this.shop_nm = shop_nm;
    }

    /**
     * Gets sid.
     *
     * @return Value for sid.
     */
    public String getSid() {
        return sid;
    }

    /**
     * Sets sid.
     *
     * @param sid New value for sid.
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * Gets cust_spouse.
     *
     * @return Value for cust_spouse.
     */
    public String getCust_spouse() {
        return cust_spouse;
    }

    /**
     * Sets cust_spouse.
     *
     * @param cust_spouse New value for cust_spouse.
     */
    public void setCust_spouse(String cust_spouse) {
        this.cust_spouse = cust_spouse;
    }

    /**
     * Gets std_cate_cd.
     *
     * @return Value for std_cate_cd.
     */
    public String getStd_cate_cd() {
        return std_cate_cd;
    }

    /**
     * Sets std_cate_cd.
     *
     * @param std_cate_cd New value for std_cate_cd.
     */
    public void setStd_cate_cd(String std_cate_cd) {
        this.std_cate_cd = std_cate_cd;
    }

    /**
     * Gets u_cookie.
     *
     * @return Value for u_cookie.
     */
    public String getU_cookie() {
        return u_cookie;
    }

    /**
     * Sets u_cookie.
     *
     * @param u_cookie New value for u_cookie.
     */
    public void setU_cookie(String u_cookie) {
        this.u_cookie = u_cookie;
    }

    /**
     * Gets udid.
     *
     * @return Value for udid.
     */
    public String getUdid() {
        return udid;
    }

    /**
     * Sets udid.
     *
     * @param udid New value for udid.
     */
    public void setUdid(String udid) {
        this.udid = udid;
    }

    /**
     * Gets uid.
     *
     * @return Value for uid.
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets uid.
     *
     * @param uid New value for uid.
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * Gets cust_cd.
     *
     * @return Value for cust_cd.
     */
    public String getCust_cd() {
        return cust_cd;
    }

    /**
     * Sets cust_cd.
     *
     * @param cust_cd New value for cust_cd.
     */
    public void setCust_cd(String cust_cd) {
        this.cust_cd = cust_cd;
    }

    /**
     * Gets cust_id.
     *
     * @return Value for cust_id.
     */
    public String getCust_id() {
        return cust_id;
    }

    /**
     * Sets cust_id.
     *
     * @param cust_id New value for cust_id.
     */
    public void setCust_id(String cust_id) {
        this.cust_id = cust_id;
    }

    /**
     * Gets useragent.
     *
     * @return Value for useragent.
     */
    public String getUseragent() {
        return useragent;
    }

    /**
     * Sets useragent.
     *
     * @param useragent New value for useragent.
     */
    public void setUseragent(String useragent) {
        this.useragent = useragent;
    }

    /**
     * Gets cust_visit_fl.
     *
     * @return Value for cust_visit_fl.
     */
    public String getCust_visit_fl() {
        return cust_visit_fl;
    }

    /**
     * Sets cust_visit_fl.
     *
     * @param cust_visit_fl New value for cust_visit_fl.
     */
    public void setCust_visit_fl(String cust_visit_fl) {
        this.cust_visit_fl = cust_visit_fl;
    }

    /**
     * Gets visit_login_fl.
     *
     * @return Value for visit_login_fl.
     */
    public String getVisit_login_fl() {
        return visit_login_fl;
    }

    /**
     * Sets visit_login_fl.
     *
     * @param visit_login_fl New value for visit_login_fl.
     */
    public void setVisit_login_fl(String visit_login_fl) {
        this.visit_login_fl = visit_login_fl;
    }

    /**
     * Gets src_chn_tp.
     *
     * @return Value for src_chn_tp.
     */
    public String getSrc_chn_tp() {
        return src_chn_tp;
    }

    /**
     * Sets src_chn_tp.
     *
     * @param src_chn_tp New value for src_chn_tp.
     */
    public void setSrc_chn_tp(String src_chn_tp) {
        this.src_chn_tp = src_chn_tp;
    }

    /**
     * Gets ord_temp_no.
     *
     * @return Value for ord_temp_no.
     */
    public String getOrd_temp_no() {
        return ord_temp_no;
    }

    /**
     * Sets ord_temp_no.
     *
     * @param ord_temp_no New value for ord_temp_no.
     */
    public void setOrd_temp_no(String ord_temp_no) {
        this.ord_temp_no = ord_temp_no;
    }

    /**
     * Gets ord_prd_affili.
     *
     * @return Value for ord_prd_affili.
     */
    public String getOrd_prd_affili() {
        return ord_prd_affili;
    }

    /**
     * Sets ord_prd_affili.
     *
     * @param ord_prd_affili New value for ord_prd_affili.
     */
    public void setOrd_prd_affili(String ord_prd_affili) {
        this.ord_prd_affili = ord_prd_affili;
    }

    /**
     * Gets infl_data.
     *
     * @return Value for infl_data.
     */
    public String getInfl_data() {
        return infl_data;
    }

    /**
     * Sets infl_data.
     *
     * @param infl_data New value for infl_data.
     */
    public void setInfl_data(String infl_data) {
        this.infl_data = infl_data;
    }

    /**
     * Gets visit_pg_seq.
     *
     * @return Value for visit_pg_seq.
     */
    public String getVisit_pg_seq() {
        return visit_pg_seq;
    }

    /**
     * Sets visit_pg_seq.
     *
     * @param visit_pg_seq New value for visit_pg_seq.
     */
    public void setVisit_pg_seq(String visit_pg_seq) {
        this.visit_pg_seq = visit_pg_seq;
    }

    /**
     * Gets cur_pg_nm.
     *
     * @return Value for cur_pg_nm.
     */
    public String getCur_pg_nm() {
        return cur_pg_nm;
    }

    /**
     * Sets cur_pg_nm.
     *
     * @param cur_pg_nm New value for cur_pg_nm.
     */
    public void setCur_pg_nm(String cur_pg_nm) {
        this.cur_pg_nm = cur_pg_nm;
    }

    /**
     * Gets prd_tp.
     *
     * @return Value for prd_tp.
     */
    public String getPrd_tp() {
        return prd_tp;
    }

    /**
     * Sets prd_tp.
     *
     * @param prd_tp New value for prd_tp.
     */
    public void setPrd_tp(String prd_tp) {
        this.prd_tp = prd_tp;
    }

    /**
     * Gets vod_cd.
     *
     * @return Value for vod_cd.
     */
    public String getVod_cd() {
        return vod_cd;
    }

    /**
     * Sets vod_cd.
     *
     * @param vod_cd New value for vod_cd.
     */
    public void setVod_cd(String vod_cd) {
        this.vod_cd = vod_cd;
    }

    public String getPgm_cd() {
        return pgm_cd;
    }

    public void setPgm_cd(String pgm_cd) {
        this.pgm_cd = pgm_cd;
    }

    public String getPartner_cd() {
        return partner_cd;
    }

    public void setPartner_cd(String partner_cd) {
        this.partner_cd = partner_cd;
    }

    public String getWeb_cate_g_cd() {
        return web_cate_g_cd;
    }

    public void setWeb_cate_g_cd(String web_cate_g_cd) {
        this.web_cate_g_cd = web_cate_g_cd;
    }

    public String getWeb_cate_l_cd() {
        return web_cate_l_cd;
    }

    public void setWeb_cate_l_cd(String web_cate_l_cd) {
        this.web_cate_l_cd = web_cate_l_cd;
    }

    public String getWeb_cate_m_cd() {
        return web_cate_m_cd;
    }

    public void setWeb_cate_m_cd(String web_cate_m_cd) {
        this.web_cate_m_cd = web_cate_m_cd;
    }

    public String getWeb_cate_s_cd() {
        return web_cate_s_cd;
    }

    public void setWeb_cate_s_cd(String web_cate_s_cd) {
        this.web_cate_s_cd = web_cate_s_cd;
    }

    /**
     * Gets host.
     *
     * @return Value for host.
     */


    public String getHost() {
        return host;
    }

    /**
     * Sets host.
     *
     * @param host New value for host.
     */
    public void setHost(String host) {
        this.host = host;
    }

    /**
     * Gets sourcetype.
     *
     * @return Value for sourcetype.
     */
    public String getSourcetype() {
        return sourcetype;
    }

    /**
     * Sets sourcetype.
     *
     * @param sourcetype New value for sourcetype.
     */

    public void setSourcetype(String sourcetype) {
        this.sourcetype = sourcetype;
    }

    public String getPrd_seq() {
        return prd_seq;
    }

    public void setPrd_seq(String prd_seq) {
        this.prd_seq = prd_seq;
    }

	/*2018.03.09 커뮤니티번호 추가 */
    public String getComm_cd() {
		return comm_cd;
	}

	public void setComm_cd(String comm_cd) {
		this.comm_cd = comm_cd;
	}
	
	/*2018.03.09 게시불번호 추가*/
	public String getBbs_cd() {
		return bbs_cd;
	}

	public void setBbs_cd(String bbs_cd) {
		this.bbs_cd = bbs_cd;
	}
	
	/* 2018.11.28 주문서타입 추가*/
	public String getOrd_sht_tp() {
		return ord_sht_tp;
	}

	public void setOrd_sht_tp(String ord_sht_tp) {
		this.ord_sht_tp = ord_sht_tp;
	}
	
    /**
     * {@inheritDoc}
     */
    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;

        if (!(o instanceof CJO_LOG_CORE))
            return false;

        CJO_LOG_CORE that = (CJO_LOG_CORE) o;

        if (log_time != null ? !log_time.equals(that.log_time) : that.log_time != null)
            return false;

        if (cust_age != null ? !cust_age.equals(that.cust_age) : that.cust_age != null)
            return false;

        if (app_cd != null ? !app_cd.equals(that.app_cd) : that.app_cd != null)
            return false;

        if (brand_cd != null ? !brand_cd.equals(that.brand_cd) : that.brand_cd != null)
            return false;

        if (intl_broad_tp != null ? !intl_broad_tp.equals(that.intl_broad_tp) : that.intl_broad_tp != null)
            return false;

        if (intl_tp != null ? !intl_tp.equals(that.intl_tp) : that.intl_tp != null)
            return false;

        if (browser_tp != null ? !browser_tp.equals(that.browser_tp) : that.browser_tp != null)
            return false;

        if (chn_cd != null ? !chn_cd.equals(that.chn_cd) : that.chn_cd != null)
            return false;

        if (click_depth1 != null ? !click_depth1.equals(that.click_depth1) : that.click_depth1 != null)
            return false;

        if (click_depth2 != null ? !click_depth2.equals(that.click_depth2) : that.click_depth2 != null)
            return false;

        if (click_depth3 != null ? !click_depth3.equals(that.click_depth3) : that.click_depth3 != null)
            return false;

        if (click_depth4 != null ? !click_depth4.equals(that.click_depth4) : that.click_depth4 != null)
            return false;

        if (click_depth5 != null ? !click_depth5.equals(that.click_depth5) : that.click_depth5 != null)
            return false;

        if (click_depth6 != null ? !click_depth6.equals(that.click_depth6) : that.click_depth6 != null)
            return false;

        if (click_depth6_seq != null ? !click_depth6_seq.equals(that.click_depth6_seq) : that.click_depth6_seq != null)
            return false;

        if (click_depth7 != null ? !click_depth7.equals(that.click_depth7) : that.click_depth7 != null)
            return false;

        if (click_depth7_seq != null ? !click_depth7_seq.equals(that.click_depth7_seq) : that.click_depth7_seq != null)
            return false;

        if (click_depth8 != null ? !click_depth8.equals(that.click_depth8) : that.click_depth8 != null)
            return false;

        if (click_depth8_seq != null ? !click_depth8_seq.equals(that.click_depth8_seq) : that.click_depth8_seq != null)
            return false;

        if (click_depth9 != null ? !click_depth9.equals(that.click_depth9) : that.click_depth9 != null)
            return false;

        if (click_depth9_seq != null ? !click_depth9_seq.equals(that.click_depth9_seq) : that.click_depth9_seq != null)
            return false;

        if (click_cd != null ? !click_cd.equals(that.click_cd) : that.click_cd != null)
            return false;

        if (cur_url_chn_tp != null ? !cur_url_chn_tp.equals(that.cur_url_chn_tp) : that.cur_url_chn_tp != null)
            return false;

        if (cur_file != null ? !cur_file.equals(that.cur_file) : that.cur_file != null)
            return false;

        if (cur_pg_info1 != null ? !cur_pg_info1.equals(that.cur_pg_info1) : that.cur_pg_info1 != null)
            return false;

        if (cur_pg_info2 != null ? !cur_pg_info2.equals(that.cur_pg_info2) : that.cur_pg_info2 != null)
            return false;

        if (cur_pg_info3 != null ? !cur_pg_info3.equals(that.cur_pg_info3) : that.cur_pg_info3 != null)
            return false;

        if (cur_pg_src_tp != null ? !cur_pg_src_tp.equals(that.cur_pg_src_tp) : that.cur_pg_src_tp != null)
            return false;

        if (cur_pg != null ? !cur_pg.equals(that.cur_pg) : that.cur_pg != null)
            return false;

        if (cur_url_domain != null ? !cur_url_domain.equals(that.cur_url_domain) : that.cur_url_domain != null)
            return false;

        if (cur_url_domain_tp != null ? !cur_url_domain_tp.equals(that.cur_url_domain_tp) : that.cur_url_domain_tp != null)
            return false;

        if (custom_pi != null ? !custom_pi.equals(that.custom_pi) : that.custom_pi != null)
            return false;

        if (date_yyyymmdd != null ? !date_yyyymmdd.equals(that.date_yyyymmdd) : that.date_yyyymmdd != null)
            return false;

        if (date_hour != null ? !date_hour.equals(that.date_hour) : that.date_hour != null)
            return false;

        if (date_mday != null ? !date_mday.equals(that.date_mday) : that.date_mday != null)
            return false;

        if (date_minute != null ? !date_minute.equals(that.date_minute) : that.date_minute != null)
            return false;

        if (date_month != null ? !date_month.equals(that.date_month) : that.date_month != null)
            return false;

        if (date_second != null ? !date_second.equals(that.date_second) : that.date_second != null)
            return false;

        if (date_wday != null ? !date_wday.equals(that.date_wday) : that.date_wday != null)
            return false;

        if (date_year != null ? !date_year.equals(that.date_year) : that.date_year != null)
            return false;

        if (empl_sale_item_fl != null ? !empl_sale_item_fl.equals(that.empl_sale_item_fl) : that.empl_sale_item_fl != null)
            return false;

        if (cust_empl_fl != null ? !cust_empl_fl.equals(that.cust_empl_fl) : that.cust_empl_fl != null)
            return false;

        if (event_cd != null ? !event_cd.equals(that.event_cd) : that.event_cd != null)
            return false;

        if (pg_load_time != null ? !pg_load_time.equals(that.pg_load_time) : that.pg_load_time != null)
            return false;

        if (cust_grade != null ? !cust_grade.equals(that.cust_grade) : that.cust_grade != null)
            return false;

        if (infl_cd != null ? !infl_cd.equals(that.infl_cd) : that.infl_cd != null)
            return false;

        if (infl_grp_cd != null ? !infl_grp_cd.equals(that.infl_grp_cd) : that.infl_grp_cd != null)
            return false;

        if (intl_pgm_cd != null ? !intl_pgm_cd.equals(that.intl_pgm_cd) : that.intl_pgm_cd != null)
            return false;

        if (log_tp != null ? !log_tp.equals(that.log_tp) : that.log_tp != null)
            return false;

        if (mobile_app_tp != null ? !mobile_app_tp.equals(that.mobile_app_tp) : that.mobile_app_tp != null)
            return false;

        if (md_cd != null ? !md_cd.equals(that.md_cd) : that.md_cd != null)
            return false;

        if (muuid != null ? !muuid.equals(that.muuid) : that.muuid != null)
            return false;

        if (ord_no != null ? !ord_no.equals(that.ord_no) : that.ord_no != null)
            return false;

        if (ord_prd_unit_cd != null ? !ord_prd_unit_cd.equals(that.ord_prd_unit_cd) : that.ord_prd_unit_cd != null)
            return false;

        if (os != null ? !os.equals(that.os) : that.os != null)
            return false;

        if (hometab_pic != null ? !hometab_pic.equals(that.hometab_pic) : that.hometab_pic != null)
            return false;

        if (ord_price != null ? !ord_price.equals(that.ord_price) : that.ord_price != null)
            return false;

        if (prd_cd != null ? !prd_cd.equals(that.prd_cd) : that.prd_cd != null)
            return false;

        if (prd_nm != null ? !prd_nm.equals(that.prd_nm) : that.prd_nm != null)
            return false;

        if (ord_prd_cnt != null ? !ord_prd_cnt.equals(that.ord_prd_cnt) : that.ord_prd_cnt != null)
            return false;

        if (ord_prd_nm != null ? !ord_prd_nm.equals(that.ord_prd_nm) : that.ord_prd_nm != null)
            return false;

        if (ref_url_chn_tp != null ? !ref_url_chn_tp.equals(that.ref_url_chn_tp) : that.ref_url_chn_tp != null)
            return false;

        if (ref_file != null ? !ref_file.equals(that.ref_file) : that.ref_file != null)
            return false;

        if (ref_pg_info1 != null ? !ref_pg_info1.equals(that.ref_pg_info1) : that.ref_pg_info1 != null)
            return false;

        if (ref_pg_info2 != null ? !ref_pg_info2.equals(that.ref_pg_info2) : that.ref_pg_info2 != null)
            return false;

        if (ref_pg_info3 != null ? !ref_pg_info3.equals(that.ref_pg_info3) : that.ref_pg_info3 != null)
            return false;

        if (ref_pg != null ? !ref_pg.equals(that.ref_pg) : that.ref_pg != null)
            return false;

        if (ref_url_domain != null ? !ref_url_domain.equals(that.ref_url_domain) : that.ref_url_domain != null)
            return false;

        if (ref_url_domain_tp != null ? !ref_url_domain_tp.equals(that.ref_url_domain_tp) : that.ref_url_domain_tp != null)
            return false;

        if (search_result != null ? !search_result.equals(that.search_result) : that.search_result != null)
            return false;

        if (search_word != null ? !search_word.equals(that.search_word) : that.search_word != null)
            return false;

        if (search_tp != null ? !search_tp.equals(that.search_tp) : that.search_tp != null)
            return false;

        if (mobile_app_service_nm != null ? !mobile_app_service_nm.equals(that.mobile_app_service_nm) : that.mobile_app_service_nm != null)
            return false;

        if (cust_gender != null ? !cust_gender.equals(that.cust_gender) : that.cust_gender != null)
            return false;

        if (shop_cd != null ? !shop_cd.equals(that.shop_cd) : that.shop_cd != null)
            return false;

        if (shop_nm != null ? !shop_nm.equals(that.shop_nm) : that.shop_nm != null)
            return false;

        if (sid != null ? !sid.equals(that.sid) : that.sid != null)
            return false;

        if (cust_spouse != null ? !cust_spouse.equals(that.cust_spouse) : that.cust_spouse != null)
            return false;

        if (std_cate_cd != null ? !std_cate_cd.equals(that.std_cate_cd) : that.std_cate_cd != null)
            return false;

        if (u_cookie != null ? !u_cookie.equals(that.u_cookie) : that.u_cookie != null)
            return false;

        if (udid != null ? !udid.equals(that.udid) : that.udid != null)
            return false;

        if (uid != null ? !uid.equals(that.uid) : that.uid != null)
            return false;

        if (cust_cd != null ? !cust_cd.equals(that.cust_cd) : that.cust_cd != null)
            return false;

        if (cust_id != null ? !cust_id.equals(that.cust_id) : that.cust_id != null)
            return false;

        if (useragent != null ? !useragent.equals(that.useragent) : that.useragent != null)
            return false;

        if (cust_visit_fl != null ? !cust_visit_fl.equals(that.cust_visit_fl) : that.cust_visit_fl != null)
            return false;

        if (visit_login_fl != null ? !visit_login_fl.equals(that.visit_login_fl) : that.visit_login_fl != null)
            return false;

        if (src_chn_tp != null ? !src_chn_tp.equals(that.src_chn_tp) : that.src_chn_tp != null)
            return false;

        if (ord_temp_no != null ? !ord_temp_no.equals(that.ord_temp_no) : that.ord_temp_no != null)
            return false;

        if (ord_prd_affili != null ? !ord_prd_affili.equals(that.ord_prd_affili) : that.ord_prd_affili != null)
            return false;

        if (infl_data != null ? !infl_data.equals(that.infl_data) : that.infl_data != null)
            return false;

        if (visit_pg_seq != null ? !visit_pg_seq.equals(that.visit_pg_seq) : that.visit_pg_seq != null)
            return false;

        if (cur_pg_nm != null ? !cur_pg_nm.equals(that.cur_pg_nm) : that.cur_pg_nm != null)
            return false;

        if (prd_tp != null ? !prd_tp.equals(that.prd_tp) : that.prd_tp != null)
            return false;

        if (vod_cd != null ? !vod_cd.equals(that.vod_cd) : that.vod_cd != null)
            return false;

        if (partner_cd != null ? !partner_cd.equals(that.partner_cd) : that.partner_cd != null)
            return false;

        if (web_cate_g_cd != null ? !web_cate_g_cd.equals(that.web_cate_g_cd) : that.web_cate_g_cd != null)
            return false;

        if (web_cate_l_cd != null ? !web_cate_l_cd.equals(that.web_cate_l_cd) : that.web_cate_l_cd != null)
            return false;

        if (web_cate_m_cd != null ? !web_cate_m_cd.equals(that.web_cate_m_cd) : that.web_cate_m_cd != null)
            return false;

        if (web_cate_s_cd != null ? !web_cate_s_cd.equals(that.web_cate_s_cd) : that.web_cate_s_cd != null)
            return false;

        if (host != null ? !host.equals(that.host) : that.host != null)
            return false;

        if (sourcetype != null ? !sourcetype.equals(that.sourcetype) : that.sourcetype != null)
            return false;

        if (prd_seq != null ? !prd_seq.equals(that.prd_seq) : that.prd_seq != null)
            return false;


        if (comm_cd != null ? !comm_cd.equals(that.comm_cd) : that.comm_cd != null)   /*2018.03.02 커뮤니티번호 추가*/
            return false;

        if (bbs_cd != null ? !bbs_cd.equals(that.bbs_cd) : that.bbs_cd != null)  /*2018.03.02 게시불번호 추가*/
            return false;
        
        if (ord_sht_tp != null ? !ord_sht_tp.equals(that.ord_sht_tp) : that.ord_sht_tp != null)  /* 2018.11.28 주문서타입 추가*/
            return false;

        
        return true;
    }

    @Override
    public CJO_LOG_CORE clone() throws CloneNotSupportedException {
        return (CJO_LOG_CORE) super.clone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public int hashCode() {
        int res = log_time != null ? log_time.hashCode() : 0;

        res = 31 * res + (cust_age != null ? cust_age.hashCode() : 0);

        res = 31 * res + (app_cd != null ? app_cd.hashCode() : 0);

        res = 31 * res + (brand_cd != null ? brand_cd.hashCode() : 0);

        res = 31 * res + (intl_broad_tp != null ? intl_broad_tp.hashCode() : 0);

        res = 31 * res + (intl_tp != null ? intl_tp.hashCode() : 0);

        res = 31 * res + (browser_tp != null ? browser_tp.hashCode() : 0);

        res = 31 * res + (chn_cd != null ? chn_cd.hashCode() : 0);

        res = 31 * res + (click_depth1 != null ? click_depth1.hashCode() : 0);

        res = 31 * res + (click_depth2 != null ? click_depth2.hashCode() : 0);

        res = 31 * res + (click_depth3 != null ? click_depth3.hashCode() : 0);

        res = 31 * res + (click_depth4 != null ? click_depth4.hashCode() : 0);

        res = 31 * res + (click_depth5 != null ? click_depth5.hashCode() : 0);

        res = 31 * res + (click_depth6 != null ? click_depth6.hashCode() : 0);

        res = 31 * res + (click_depth6_seq != null ? click_depth6_seq.hashCode() : 0);

        res = 31 * res + (click_depth7 != null ? click_depth7.hashCode() : 0);

        res = 31 * res + (click_depth7_seq != null ? click_depth7_seq.hashCode() : 0);

        res = 31 * res + (click_depth8 != null ? click_depth8.hashCode() : 0);

        res = 31 * res + (click_depth8_seq != null ? click_depth8_seq.hashCode() : 0);

        res = 31 * res + (click_depth9 != null ? click_depth9.hashCode() : 0);

        res = 31 * res + (click_depth9_seq != null ? click_depth9_seq.hashCode() : 0);

        res = 31 * res + (click_cd != null ? click_cd.hashCode() : 0);

        res = 31 * res + (cur_url_chn_tp != null ? cur_url_chn_tp.hashCode() : 0);

        res = 31 * res + (cur_file != null ? cur_file.hashCode() : 0);

        res = 31 * res + (cur_pg_info1 != null ? cur_pg_info1.hashCode() : 0);

        res = 31 * res + (cur_pg_info2 != null ? cur_pg_info2.hashCode() : 0);

        res = 31 * res + (cur_pg_info3 != null ? cur_pg_info3.hashCode() : 0);

        res = 31 * res + (cur_pg_src_tp != null ? cur_pg_src_tp.hashCode() : 0);

        res = 31 * res + (cur_pg != null ? cur_pg.hashCode() : 0);

        res = 31 * res + (cur_url_domain != null ? cur_url_domain.hashCode() : 0);

        res = 31 * res + (cur_url_domain_tp != null ? cur_url_domain_tp.hashCode() : 0);

        res = 31 * res + (custom_pi != null ? custom_pi.hashCode() : 0);

        res = 31 * res + (date_yyyymmdd != null ? date_yyyymmdd.hashCode() : 0);

        res = 31 * res + (date_hour != null ? date_hour.hashCode() : 0);

        res = 31 * res + (date_mday != null ? date_mday.hashCode() : 0);

        res = 31 * res + (date_minute != null ? date_minute.hashCode() : 0);

        res = 31 * res + (date_month != null ? date_month.hashCode() : 0);

        res = 31 * res + (date_second != null ? date_second.hashCode() : 0);

        res = 31 * res + (date_wday != null ? date_wday.hashCode() : 0);

        res = 31 * res + (date_year != null ? date_year.hashCode() : 0);

        res = 31 * res + (empl_sale_item_fl != null ? empl_sale_item_fl.hashCode() : 0);

        res = 31 * res + (cust_empl_fl != null ? cust_empl_fl.hashCode() : 0);

        res = 31 * res + (event_cd != null ? event_cd.hashCode() : 0);

        res = 31 * res + (pg_load_time != null ? pg_load_time.hashCode() : 0);

        res = 31 * res + (cust_grade != null ? cust_grade.hashCode() : 0);

        res = 31 * res + (infl_cd != null ? infl_cd.hashCode() : 0);

        res = 31 * res + (infl_grp_cd != null ? infl_grp_cd.hashCode() : 0);

        res = 31 * res + (intl_pgm_cd != null ? intl_pgm_cd.hashCode() : 0);

        res = 31 * res + (log_tp != null ? log_tp.hashCode() : 0);

        res = 31 * res + (mobile_app_tp != null ? mobile_app_tp.hashCode() : 0);

        res = 31 * res + (md_cd != null ? md_cd.hashCode() : 0);

        res = 31 * res + (muuid != null ? muuid.hashCode() : 0);

        res = 31 * res + (ord_no != null ? ord_no.hashCode() : 0);

        res = 31 * res + (ord_prd_unit_cd != null ? ord_prd_unit_cd.hashCode() : 0);

        res = 31 * res + (os != null ? os.hashCode() : 0);

        res = 31 * res + (hometab_pic != null ? hometab_pic.hashCode() : 0);

        res = 31 * res + (ord_price != null ? ord_price.hashCode() : 0);

        res = 31 * res + (prd_cd != null ? prd_cd.hashCode() : 0);

        res = 31 * res + (prd_nm != null ? prd_nm.hashCode() : 0);

        res = 31 * res + (ord_prd_cnt != null ? ord_prd_cnt.hashCode() : 0);

        res = 31 * res + (ord_prd_nm != null ? ord_prd_nm.hashCode() : 0);

        res = 31 * res + (ref_url_chn_tp != null ? ref_url_chn_tp.hashCode() : 0);

        res = 31 * res + (ref_file != null ? ref_file.hashCode() : 0);

        res = 31 * res + (ref_pg_info1 != null ? ref_pg_info1.hashCode() : 0);

        res = 31 * res + (ref_pg_info2 != null ? ref_pg_info2.hashCode() : 0);

        res = 31 * res + (ref_pg_info3 != null ? ref_pg_info3.hashCode() : 0);

        res = 31 * res + (ref_pg != null ? ref_pg.hashCode() : 0);

        res = 31 * res + (ref_url_domain != null ? ref_url_domain.hashCode() : 0);

        res = 31 * res + (ref_url_domain_tp != null ? ref_url_domain_tp.hashCode() : 0);

        res = 31 * res + (search_result != null ? search_result.hashCode() : 0);

        res = 31 * res + (search_word != null ? search_word.hashCode() : 0);

        res = 31 * res + (search_tp != null ? search_tp.hashCode() : 0);

        res = 31 * res + (mobile_app_service_nm != null ? mobile_app_service_nm.hashCode() : 0);

        res = 31 * res + (cust_gender != null ? cust_gender.hashCode() : 0);

        res = 31 * res + (shop_cd != null ? shop_cd.hashCode() : 0);

        res = 31 * res + (shop_nm != null ? shop_nm.hashCode() : 0);

        res = 31 * res + (sid != null ? sid.hashCode() : 0);

        res = 31 * res + (cust_spouse != null ? cust_spouse.hashCode() : 0);

        res = 31 * res + (std_cate_cd != null ? std_cate_cd.hashCode() : 0);

        res = 31 * res + (u_cookie != null ? u_cookie.hashCode() : 0);

        res = 31 * res + (udid != null ? udid.hashCode() : 0);

        res = 31 * res + (uid != null ? uid.hashCode() : 0);

        res = 31 * res + (cust_cd != null ? cust_cd.hashCode() : 0);

        res = 31 * res + (cust_id != null ? cust_id.hashCode() : 0);

        res = 31 * res + (useragent != null ? useragent.hashCode() : 0);

        res = 31 * res + (cust_visit_fl != null ? cust_visit_fl.hashCode() : 0);

        res = 31 * res + (visit_login_fl != null ? visit_login_fl.hashCode() : 0);

        res = 31 * res + (src_chn_tp != null ? src_chn_tp.hashCode() : 0);

        res = 31 * res + (ord_temp_no != null ? ord_temp_no.hashCode() : 0);

        res = 31 * res + (ord_prd_affili != null ? ord_prd_affili.hashCode() : 0);

        res = 31 * res + (infl_data != null ? infl_data.hashCode() : 0);

        res = 31 * res + (visit_pg_seq != null ? visit_pg_seq.hashCode() : 0);

        res = 31 * res + (cur_pg_nm != null ? cur_pg_nm.hashCode() : 0);

        res = 31 * res + (prd_tp != null ? prd_tp.hashCode() : 0);

        res = 31 * res + (vod_cd != null ? vod_cd.hashCode() : 0);

        res = 31 * res + (partner_cd != null ? partner_cd.hashCode() : 0);

        res = 31 * res + (web_cate_g_cd != null ? web_cate_g_cd.hashCode() : 0);

        res = 31 * res + (web_cate_l_cd != null ? web_cate_l_cd.hashCode() : 0);

        res = 31 * res + (web_cate_m_cd != null ? web_cate_m_cd.hashCode() : 0);

        res = 31 * res + (web_cate_s_cd != null ? web_cate_s_cd.hashCode() : 0);

        res = 31 * res + (host != null ? host.hashCode() : 0);

        res = 31 * res + (sourcetype != null ? sourcetype.hashCode() : 0);

        res = 31 * res + (prd_seq != null ? prd_seq.hashCode() : 0);
        
        
        res = 31 * res + (comm_cd != null ? comm_cd.hashCode() : 0);   /*2018.03.09 커뮤니티번호 추가*/
        
        res = 31 * res + (bbs_cd != null ? bbs_cd.hashCode() : 0); /*2018.03.09 게시불번호 추가*/
        
        res = 31 * res + (ord_sht_tp != null ? ord_sht_tp.hashCode() : 0); /* 2018.11.28 주문서타입 추가*/

        return res;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String toString() {
        return "CJO_LOG_CORE [log_time=" + log_time +
                ", cust_age=" + cust_age +
                ", app_cd=" + app_cd +
                ", brand_cd=" + brand_cd +
                ", intl_broad_tp=" + intl_broad_tp +
                ", intl_tp=" + intl_tp +
                ", browser_tp=" + browser_tp +
                ", chn_cd=" + chn_cd +
                ", click_depth1=" + click_depth1 +
                ", click_depth2=" + click_depth2 +
                ", click_depth3=" + click_depth3 +
                ", click_depth4=" + click_depth4 +
                ", click_depth5=" + click_depth5 +
                ", click_depth6=" + click_depth6 +
                ", click_depth6_seq=" + click_depth6_seq +
                ", click_depth7=" + click_depth7 +
                ", click_depth7_seq=" + click_depth7_seq +
                ", click_depth8=" + click_depth8 +
                ", click_depth8_seq=" + click_depth8_seq +
                ", click_depth9=" + click_depth9 +
                ", click_depth9_seq=" + click_depth9_seq +
                ", click_cd=" + click_cd +
                ", cur_url_chn_tp=" + cur_url_chn_tp +
                ", cur_file=" + cur_file +
                ", cur_pg_info1=" + cur_pg_info1 +
                ", cur_pg_info2=" + cur_pg_info2 +
                ", cur_pg_info3=" + cur_pg_info3 +
                ", cur_pg_src_tp=" + cur_pg_src_tp +
                ", cur_pg=" + cur_pg +
                ", cur_url_domain=" + cur_url_domain +
                ", cur_url_domain_tp=" + cur_url_domain_tp +
                ", custom_pi=" + custom_pi +
                ", date_yyyymmdd=" + date_yyyymmdd +
                ", date_hour=" + date_hour +
                ", date_mday=" + date_mday +
                ", date_minute=" + date_minute +
                ", date_month=" + date_month +
                ", date_second=" + date_second +
                ", date_wday=" + date_wday +
                ", date_year=" + date_year +
                ", empl_sale_item_fl=" + empl_sale_item_fl +
                ", cust_empl_fl=" + cust_empl_fl +
                ", event_cd=" + event_cd +
                ", pg_load_time=" + pg_load_time +
                ", cust_grade=" + cust_grade +
                ", infl_cd=" + infl_cd +
                ", infl_grp_cd=" + infl_grp_cd +
                ", intl_pgm_cd=" + intl_pgm_cd +
                ", log_tp=" + log_tp +
                ", mobile_app_tp=" + mobile_app_tp +
                ", md_cd=" + md_cd +
                ", muuid=" + muuid +
                ", ord_no=" + ord_no +
                ", ord_prd_unit_cd=" + ord_prd_unit_cd +
                ", os=" + os +
                ", hometab_pic=" + hometab_pic +
                ", ord_price=" + ord_price +
                ", prd_cd=" + prd_cd +
                ", prd_nm=" + prd_nm +
                ", ord_prd_cnt=" + ord_prd_cnt +
                ", ord_prd_nm=" + ord_prd_nm +
                ", ref_url_chn_tp=" + ref_url_chn_tp +
                ", ref_file=" + ref_file +
                ", ref_pg_info1=" + ref_pg_info1 +
                ", ref_pg_info2=" + ref_pg_info2 +
                ", ref_pg_info3=" + ref_pg_info3 +
                ", ref_pg=" + ref_pg +
                ", ref_url_domain=" + ref_url_domain +
                ", ref_url_domain_tp=" + ref_url_domain_tp +
                ", search_result=" + search_result +
                ", search_word=" + search_word +
                ", search_tp=" + search_tp +
                ", mobile_app_service_nm=" + mobile_app_service_nm +
                ", cust_gender=" + cust_gender +
                ", shop_cd=" + shop_cd +
                ", shop_nm=" + shop_nm +
                ", sid=" + sid +
                ", cust_spouse=" + cust_spouse +
                ", std_cate_cd=" + std_cate_cd +
                ", u_cookie=" + u_cookie +
                ", udid=" + udid +
                ", uid=" + uid +
                ", cust_cd=" + cust_cd +
                ", cust_id=" + cust_id +
                ", useragent=" + useragent +
                ", cust_visit_fl=" + cust_visit_fl +
                ", visit_login_fl=" + visit_login_fl +
                ", src_chn_tp=" + src_chn_tp +
                ", ord_temp_no=" + ord_temp_no +
                ", ord_prd_affili=" + ord_prd_affili +
                ", infl_data=" + infl_data +
                ", visit_pg_seq=" + visit_pg_seq +
                ", cur_pg_nm=" + cur_pg_nm +
                ", prd_tp=" + prd_tp +
                ", vod_cd=" + vod_cd +
                ", partner_cd=" + partner_cd +
                ", web_cate_g_cd=" + web_cate_g_cd +
                ", web_cate_l_cd=" + web_cate_l_cd +
                ", web_cate_m_cd=" + web_cate_m_cd +
                ", web_cate_s_cd=" + web_cate_s_cd +
                ", host=" + host +
                ", sourcetype=" + sourcetype +
                ", prd_seq=" + prd_seq +
                ", comm_cd=" + comm_cd + /*2018.03.09 커뮤니티번호 추가*/
                ", bbs_cd=" + bbs_cd +   /*2018.03.09 게시불번호 추가*/ 
                ", ord_sht_tp=" + ord_sht_tp +   /* 2018.11.28 주문서타입 추가*/ 
                "]";
    }




}

